; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -aarch64-sve-vector-bits-min=256  < %s | FileCheck %s -check-prefixes=CHECK,VBITS_GE_256
; RUN: llc -aarch64-sve-vector-bits-min=512  < %s | FileCheck %s -check-prefixes=CHECK,VBITS_GE_512
; RUN: llc -aarch64-sve-vector-bits-min=2048 < %s | FileCheck %s -check-prefixes=CHECK,VBITS_GE_512

target triple = "aarch64-unknown-linux-gnu"

;
; USRA disjoint OR
;

define <8 x i8> @usra_disjoint_or8xi8(<8 x i8> %a, <8 x i8> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_or8xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    usra v0.8b, v1.8b, #4
; CHECK-NEXT:    ret
  %shift = lshr <8 x i8> %b, splat(i8 4)
  %res = or disjoint <8 x i8> %a, %shift
  ret <8 x i8> %res
}

define <16 x i8> @usra_disjoint_or16xi8(<16 x i8> %a, <16 x i8> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_or16xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    usra v0.16b, v1.16b, #4
; CHECK-NEXT:    ret
  %shift = lshr <16 x i8> %b, splat(i8 4)
  %res = or disjoint <16 x i8> %a, %shift
  ret <16 x i8> %res
}

define void @usra_disjoint_or32xi8(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_or32xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl32
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1]
; CHECK-NEXT:    usra z0.b, z1.b, #4
; CHECK-NEXT:    st1b { z0.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <32 x i8>, ptr %a
  %vb = load <32 x i8>, ptr %b
  %shift = lshr <32 x i8> %vb, splat(i8 4)
  %res = or disjoint <32 x i8> %va, %shift
  store <32 x i8> %res, ptr %a
  ret void
}

define void @usra_disjoint_or64xi8(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: usra_disjoint_or64xi8:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.b, vl32
; VBITS_GE_256-NEXT:    mov w8, #32 // =0x20
; VBITS_GE_256-NEXT:    ld1b { z0.b }, p0/z, [x0, x8]
; VBITS_GE_256-NEXT:    ld1b { z1.b }, p0/z, [x1, x8]
; VBITS_GE_256-NEXT:    ld1b { z2.b }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1b { z3.b }, p0/z, [x1]
; VBITS_GE_256-NEXT:    usra z0.b, z1.b, #4
; VBITS_GE_256-NEXT:    usra z2.b, z3.b, #4
; VBITS_GE_256-NEXT:    st1b { z0.b }, p0, [x0, x8]
; VBITS_GE_256-NEXT:    st1b { z2.b }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: usra_disjoint_or64xi8:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.b, vl64
; VBITS_GE_512-NEXT:    ld1b { z0.b }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1b { z1.b }, p0/z, [x1]
; VBITS_GE_512-NEXT:    usra z0.b, z1.b, #4
; VBITS_GE_512-NEXT:    st1b { z0.b }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <64 x i8>, ptr %a
  %vb = load <64 x i8>, ptr %b
  %shift = lshr <64 x i8> %vb, splat(i8 4)
  %res = or disjoint <64 x i8> %va, %shift
  store <64 x i8> %res, ptr %a
  ret void
}

define void @usra_disjoint_or128xi8(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: usra_disjoint_or128xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl128
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1]
; CHECK-NEXT:    usra z0.b, z1.b, #4
; CHECK-NEXT:    st1b { z0.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <128 x i8>, ptr %a
  %vb = load <128 x i8>, ptr %b
  %shift = lshr <128 x i8> %vb, splat(i8 4)
  %res = or disjoint <128 x i8> %va, %shift
  store <128 x i8> %res, ptr %a
  ret void
}

define void @usra_disjoint_or256xi8(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: usra_disjoint_or256xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl256
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1]
; CHECK-NEXT:    usra z0.b, z1.b, #4
; CHECK-NEXT:    st1b { z0.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <256 x i8>, ptr %a
  %vb = load <256 x i8>, ptr %b
  %shift = lshr <256 x i8> %vb, splat(i8 4)
  %res = or disjoint <256 x i8> %va, %shift
  store <256 x i8> %res, ptr %a
  ret void
}

define <4 x i16> @usra_disjoint_or4xi16(<4 x i16> %a, <4 x i16> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_or4xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    usra v0.4h, v1.4h, #4
; CHECK-NEXT:    ret
  %shift = lshr <4 x i16> %b, splat(i16 4)
  %res = or disjoint <4 x i16> %a, %shift
  ret <4 x i16> %res
}

define <8 x i16> @usra_disjoint_or8xi16(<8 x i16> %a, <8 x i16> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_or8xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    usra v0.8h, v1.8h, #4
; CHECK-NEXT:    ret
  %shift = lshr <8 x i16> %b, splat(i16 4)
  %res = or disjoint <8 x i16> %a, %shift
  ret <8 x i16> %res
}

define void @usra_disjoint_or16xi16(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_or16xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl16
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    ld1h { z1.h }, p0/z, [x1]
; CHECK-NEXT:    usra z0.h, z1.h, #4
; CHECK-NEXT:    st1h { z0.h }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <16 x i16>, ptr %a
  %vb = load <16 x i16>, ptr %b
  %shift = lshr <16 x i16> %vb, splat(i16 4)
  %res = or disjoint <16 x i16> %va, %shift
  store <16 x i16> %res, ptr %a
  ret void
}

define void @usra_disjoint_or32xi16(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: usra_disjoint_or32xi16:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.h, vl16
; VBITS_GE_256-NEXT:    mov x8, #16 // =0x10
; VBITS_GE_256-NEXT:    ld1h { z0.h }, p0/z, [x0, x8, lsl #1]
; VBITS_GE_256-NEXT:    ld1h { z1.h }, p0/z, [x1, x8, lsl #1]
; VBITS_GE_256-NEXT:    ld1h { z2.h }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1h { z3.h }, p0/z, [x1]
; VBITS_GE_256-NEXT:    usra z0.h, z1.h, #4
; VBITS_GE_256-NEXT:    usra z2.h, z3.h, #4
; VBITS_GE_256-NEXT:    st1h { z0.h }, p0, [x0, x8, lsl #1]
; VBITS_GE_256-NEXT:    st1h { z2.h }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: usra_disjoint_or32xi16:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.h, vl32
; VBITS_GE_512-NEXT:    ld1h { z0.h }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1h { z1.h }, p0/z, [x1]
; VBITS_GE_512-NEXT:    usra z0.h, z1.h, #4
; VBITS_GE_512-NEXT:    st1h { z0.h }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <32 x i16>, ptr %a
  %vb = load <32 x i16>, ptr %b
  %shift = lshr <32 x i16> %vb, splat(i16 4)
  %res = or disjoint <32 x i16> %va, %shift
  store <32 x i16> %res, ptr %a
  ret void
}

define void @usra_disjoint_or64xi16(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: usra_disjoint_or64xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl64
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    ld1h { z1.h }, p0/z, [x1]
; CHECK-NEXT:    usra z0.h, z1.h, #4
; CHECK-NEXT:    st1h { z0.h }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <64 x i16>, ptr %a
  %vb = load <64 x i16>, ptr %b
  %shift = lshr <64 x i16> %vb, splat(i16 4)
  %res = or disjoint <64 x i16> %va, %shift
  store <64 x i16> %res, ptr %a
  ret void
}

define void @usra_disjoint_or128xi16(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: usra_disjoint_or128xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl128
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    ld1h { z1.h }, p0/z, [x1]
; CHECK-NEXT:    usra z0.h, z1.h, #4
; CHECK-NEXT:    st1h { z0.h }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <128 x i16>, ptr %a
  %vb = load <128 x i16>, ptr %b
  %shift = lshr <128 x i16> %vb, splat(i16 4)
  %res = or disjoint <128 x i16> %va, %shift
  store <128 x i16> %res, ptr %a
  ret void
}

define <2 x i32> @usra_disjoint_or2xi32(<2 x i32> %a, <2 x i32> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_or2xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    usra v0.2s, v1.2s, #4
; CHECK-NEXT:    ret
  %shift = lshr <2 x i32> %b, splat(i32 4)
  %res = or disjoint <2 x i32> %a, %shift
  ret <2 x i32> %res
}

define <4 x i32> @usra_disjoint_or4xi32(<4 x i32> %a, <4 x i32> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_or4xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    usra v0.4s, v1.4s, #4
; CHECK-NEXT:    ret
  %shift = lshr <4 x i32> %b, splat(i32 4)
  %res = or disjoint <4 x i32> %a, %shift
  ret <4 x i32> %res
}

define void @usra_disjoint_or8xi32(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_or8xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s, vl8
; CHECK-NEXT:    ld1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    ld1w { z1.s }, p0/z, [x1]
; CHECK-NEXT:    usra z0.s, z1.s, #4
; CHECK-NEXT:    st1w { z0.s }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <8 x i32>, ptr %a
  %vb = load <8 x i32>, ptr %b
  %shift = lshr <8 x i32> %vb, splat(i32 4)
  %res = or disjoint <8 x i32> %va, %shift
  store <8 x i32> %res, ptr %a
  ret void
}

define void @usra_disjoint_or16xi32(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: usra_disjoint_or16xi32:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.s, vl8
; VBITS_GE_256-NEXT:    mov x8, #8 // =0x8
; VBITS_GE_256-NEXT:    ld1w { z0.s }, p0/z, [x0, x8, lsl #2]
; VBITS_GE_256-NEXT:    ld1w { z1.s }, p0/z, [x1, x8, lsl #2]
; VBITS_GE_256-NEXT:    ld1w { z2.s }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1w { z3.s }, p0/z, [x1]
; VBITS_GE_256-NEXT:    usra z0.s, z1.s, #4
; VBITS_GE_256-NEXT:    usra z2.s, z3.s, #4
; VBITS_GE_256-NEXT:    st1w { z0.s }, p0, [x0, x8, lsl #2]
; VBITS_GE_256-NEXT:    st1w { z2.s }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: usra_disjoint_or16xi32:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.s, vl16
; VBITS_GE_512-NEXT:    ld1w { z0.s }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1w { z1.s }, p0/z, [x1]
; VBITS_GE_512-NEXT:    usra z0.s, z1.s, #4
; VBITS_GE_512-NEXT:    st1w { z0.s }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <16 x i32>, ptr %a
  %vb = load <16 x i32>, ptr %b
  %shift = lshr <16 x i32> %vb, splat(i32 4)
  %res = or disjoint <16 x i32> %va, %shift
  store <16 x i32> %res, ptr %a
  ret void
}

define void @usra_disjoint_or32xi32(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: usra_disjoint_or32xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s, vl32
; CHECK-NEXT:    ld1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    ld1w { z1.s }, p0/z, [x1]
; CHECK-NEXT:    usra z0.s, z1.s, #4
; CHECK-NEXT:    st1w { z0.s }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <32 x i32>, ptr %a
  %vb = load <32 x i32>, ptr %b
  %shift = lshr <32 x i32> %vb, splat(i32 4)
  %res = or disjoint <32 x i32> %va, %shift
  store <32 x i32> %res, ptr %a
  ret void
}

define void @usra_disjoint_or64xi32(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: usra_disjoint_or64xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s, vl64
; CHECK-NEXT:    ld1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    ld1w { z1.s }, p0/z, [x1]
; CHECK-NEXT:    usra z0.s, z1.s, #4
; CHECK-NEXT:    st1w { z0.s }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <64 x i32>, ptr %a
  %vb = load <64 x i32>, ptr %b
  %shift = lshr <64 x i32> %vb, splat(i32 4)
  %res = or disjoint <64 x i32> %va, %shift
  store <64 x i32> %res, ptr %a
  ret void
}

define <1 x i64> @usra_disjoint_or1xi64(<1 x i64> %a, <1 x i64> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_or1xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    usra d0, d1, #4
; CHECK-NEXT:    ret
  %shift = lshr <1 x i64> %b, splat(i64 4)
  %res = or disjoint <1 x i64> %a, %shift
  ret <1 x i64> %res
}

define <2 x i64> @usra_disjoint_or2xi64(<2 x i64> %a, <2 x i64> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_or2xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    usra v0.2d, v1.2d, #4
; CHECK-NEXT:    ret
  %shift = lshr <2 x i64> %b, splat(i64 4)
  %res = or disjoint <2 x i64> %a, %shift
  ret <2 x i64> %res
}

define void @usra_disjoint_or4xi64(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_or4xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d, vl4
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    ld1d { z1.d }, p0/z, [x1]
; CHECK-NEXT:    usra z0.d, z1.d, #4
; CHECK-NEXT:    st1d { z0.d }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <4 x i64>, ptr %a
  %vb = load <4 x i64>, ptr %b
  %shift = lshr <4 x i64> %vb, splat(i64 4)
  %res = or disjoint <4 x i64> %va, %shift
  store <4 x i64> %res, ptr %a
  ret void
}

define void @usra_disjoint_or8xi64(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: usra_disjoint_or8xi64:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.d, vl4
; VBITS_GE_256-NEXT:    mov x8, #4 // =0x4
; VBITS_GE_256-NEXT:    ld1d { z0.d }, p0/z, [x0, x8, lsl #3]
; VBITS_GE_256-NEXT:    ld1d { z1.d }, p0/z, [x1, x8, lsl #3]
; VBITS_GE_256-NEXT:    ld1d { z2.d }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1d { z3.d }, p0/z, [x1]
; VBITS_GE_256-NEXT:    usra z0.d, z1.d, #4
; VBITS_GE_256-NEXT:    usra z2.d, z3.d, #4
; VBITS_GE_256-NEXT:    st1d { z0.d }, p0, [x0, x8, lsl #3]
; VBITS_GE_256-NEXT:    st1d { z2.d }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: usra_disjoint_or8xi64:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.d, vl8
; VBITS_GE_512-NEXT:    ld1d { z0.d }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1d { z1.d }, p0/z, [x1]
; VBITS_GE_512-NEXT:    usra z0.d, z1.d, #4
; VBITS_GE_512-NEXT:    st1d { z0.d }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <8 x i64>, ptr %a
  %vb = load <8 x i64>, ptr %b
  %shift = lshr <8 x i64> %vb, splat(i64 4)
  %res = or disjoint <8 x i64> %va, %shift
  store <8 x i64> %res, ptr %a
  ret void
}

define void @usra_disjoint_or16xi64(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: usra_disjoint_or16xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d, vl16
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    ld1d { z1.d }, p0/z, [x1]
; CHECK-NEXT:    usra z0.d, z1.d, #4
; CHECK-NEXT:    st1d { z0.d }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <16 x i64>, ptr %a
  %vb = load <16 x i64>, ptr %b
  %shift = lshr <16 x i64> %vb, splat(i64 4)
  %res = or disjoint <16 x i64> %va, %shift
  store <16 x i64> %res, ptr %a
  ret void
}

define void @usra_disjoint_or32xi64(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: usra_disjoint_or32xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d, vl32
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    ld1d { z1.d }, p0/z, [x1]
; CHECK-NEXT:    usra z0.d, z1.d, #4
; CHECK-NEXT:    st1d { z0.d }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <32 x i64>, ptr %a
  %vb = load <32 x i64>, ptr %b
  %shift = lshr <32 x i64> %vb, splat(i64 4)
  %res = or disjoint <32 x i64> %va, %shift
  store <32 x i64> %res, ptr %a
  ret void
}

;
; USRA legacy memory-form disjoint OR
;

define void @usra2_disjoint_or32i8(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra2_disjoint_or32i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl32
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1]
; CHECK-NEXT:    usra z0.b, z1.b, #4
; CHECK-NEXT:    st1b { z0.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <32 x i8>, ptr %a, align 32
  %vb = load <32 x i8>, ptr %b, align 32
  %shift = lshr <32 x i8> %vb, splat(i8 4)
  %res = or disjoint <32 x i8> %va, %shift
  store <32 x i8> %res, ptr %a, align 32
  ret void
}

define void @usra2_disjoint_or64i8(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra2_disjoint_or64i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl32
; CHECK-NEXT:    mov w8, #32 // =0x20
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0, x8]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1, x8]
; CHECK-NEXT:    ld1b { z2.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z3.b }, p0/z, [x1]
; CHECK-NEXT:    usra z0.b, z1.b, #4
; CHECK-NEXT:    usra z2.b, z3.b, #4
; CHECK-NEXT:    st1b { z0.b }, p0, [x0, x8]
; CHECK-NEXT:    st1b { z2.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <64 x i8>, ptr %a, align 32
  %vb = load <64 x i8>, ptr %b, align 32
  %shift = lshr <64 x i8> %vb, splat(i8 4)
  %res = or disjoint <64 x i8> %va, %shift
  store <64 x i8> %res, ptr %a, align 32
  ret void
}

define void @usra2_disjoint_or128i8(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra2_disjoint_or128i8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl32
; CHECK-NEXT:    mov w8, #64 // =0x40
; CHECK-NEXT:    mov w9, #96 // =0x60
; CHECK-NEXT:    mov w10, #32 // =0x20
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0, x8]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1, x8]
; CHECK-NEXT:    ld1b { z2.b }, p0/z, [x0, x9]
; CHECK-NEXT:    ld1b { z3.b }, p0/z, [x1, x9]
; CHECK-NEXT:    ld1b { z4.b }, p0/z, [x0, x10]
; CHECK-NEXT:    ld1b { z5.b }, p0/z, [x1, x10]
; CHECK-NEXT:    ld1b { z6.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z7.b }, p0/z, [x1]
; CHECK-NEXT:    usra z0.b, z1.b, #4
; CHECK-NEXT:    usra z2.b, z3.b, #4
; CHECK-NEXT:    usra z4.b, z5.b, #4
; CHECK-NEXT:    usra z6.b, z7.b, #4
; CHECK-NEXT:    st1b { z0.b }, p0, [x0, x8]
; CHECK-NEXT:    st1b { z2.b }, p0, [x0, x9]
; CHECK-NEXT:    st1b { z4.b }, p0, [x0, x10]
; CHECK-NEXT:    st1b { z6.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <128 x i8>, ptr %a, align 32
  %vb = load <128 x i8>, ptr %b, align 32
  %shift = lshr <128 x i8> %vb, splat(i8 4)
  %res = or disjoint <128 x i8> %va, %shift
  store <128 x i8> %res, ptr %a, align 32
  ret void
}

;
; SSRA disjoint OR
;

define <8 x i8> @ssra_disjoint_or8xi8(<8 x i8> %a, <8 x i8> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_or8xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ssra v0.8b, v1.8b, #4
; CHECK-NEXT:    ret
  %shift = ashr <8 x i8> %b, splat(i8 4)
  %res = or disjoint <8 x i8> %a, %shift
  ret <8 x i8> %res
}

define <16 x i8> @ssra_disjoint_or16xi8(<16 x i8> %a, <16 x i8> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_or16xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ssra v0.16b, v1.16b, #4
; CHECK-NEXT:    ret
  %shift = ashr <16 x i8> %b, splat(i8 4)
  %res = or disjoint <16 x i8> %a, %shift
  ret <16 x i8> %res
}

define void @ssra_disjoint_or32xi8(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_or32xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl32
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1]
; CHECK-NEXT:    ssra z0.b, z1.b, #4
; CHECK-NEXT:    st1b { z0.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <32 x i8>, ptr %a
  %vb = load <32 x i8>, ptr %b
  %shift = ashr <32 x i8> %vb, splat(i8 4)
  %res = or disjoint <32 x i8> %va, %shift
  store <32 x i8> %res, ptr %a
  ret void
}

define void @ssra_disjoint_or64xi8(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: ssra_disjoint_or64xi8:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.b, vl32
; VBITS_GE_256-NEXT:    mov w8, #32 // =0x20
; VBITS_GE_256-NEXT:    ld1b { z0.b }, p0/z, [x0, x8]
; VBITS_GE_256-NEXT:    ld1b { z1.b }, p0/z, [x1, x8]
; VBITS_GE_256-NEXT:    ld1b { z2.b }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1b { z3.b }, p0/z, [x1]
; VBITS_GE_256-NEXT:    ssra z0.b, z1.b, #4
; VBITS_GE_256-NEXT:    ssra z2.b, z3.b, #4
; VBITS_GE_256-NEXT:    st1b { z0.b }, p0, [x0, x8]
; VBITS_GE_256-NEXT:    st1b { z2.b }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: ssra_disjoint_or64xi8:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.b, vl64
; VBITS_GE_512-NEXT:    ld1b { z0.b }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1b { z1.b }, p0/z, [x1]
; VBITS_GE_512-NEXT:    ssra z0.b, z1.b, #4
; VBITS_GE_512-NEXT:    st1b { z0.b }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <64 x i8>, ptr %a
  %vb = load <64 x i8>, ptr %b
  %shift = ashr <64 x i8> %vb, splat(i8 4)
  %res = or disjoint <64 x i8> %va, %shift
  store <64 x i8> %res, ptr %a
  ret void
}

define void @ssra_disjoint_or128xi8(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: ssra_disjoint_or128xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl128
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1]
; CHECK-NEXT:    ssra z0.b, z1.b, #4
; CHECK-NEXT:    st1b { z0.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <128 x i8>, ptr %a
  %vb = load <128 x i8>, ptr %b
  %shift = ashr <128 x i8> %vb, splat(i8 4)
  %res = or disjoint <128 x i8> %va, %shift
  store <128 x i8> %res, ptr %a
  ret void
}

define void @ssra_disjoint_or256xi8(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: ssra_disjoint_or256xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl256
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1]
; CHECK-NEXT:    ssra z0.b, z1.b, #4
; CHECK-NEXT:    st1b { z0.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <256 x i8>, ptr %a
  %vb = load <256 x i8>, ptr %b
  %shift = ashr <256 x i8> %vb, splat(i8 4)
  %res = or disjoint <256 x i8> %va, %shift
  store <256 x i8> %res, ptr %a
  ret void
}

define <4 x i16> @ssra_disjoint_or4xi16(<4 x i16> %a, <4 x i16> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_or4xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ssra v0.4h, v1.4h, #4
; CHECK-NEXT:    ret
  %shift = ashr <4 x i16> %b, splat(i16 4)
  %res = or disjoint <4 x i16> %a, %shift
  ret <4 x i16> %res
}

define <8 x i16> @ssra_disjoint_or8xi16(<8 x i16> %a, <8 x i16> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_or8xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ssra v0.8h, v1.8h, #4
; CHECK-NEXT:    ret
  %shift = ashr <8 x i16> %b, splat(i16 4)
  %res = or disjoint <8 x i16> %a, %shift
  ret <8 x i16> %res
}

define void @ssra_disjoint_or16xi16(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_or16xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl16
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    ld1h { z1.h }, p0/z, [x1]
; CHECK-NEXT:    ssra z0.h, z1.h, #4
; CHECK-NEXT:    st1h { z0.h }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <16 x i16>, ptr %a
  %vb = load <16 x i16>, ptr %b
  %shift = ashr <16 x i16> %vb, splat(i16 4)
  %res = or disjoint <16 x i16> %va, %shift
  store <16 x i16> %res, ptr %a
  ret void
}

define void @ssra_disjoint_or32xi16(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: ssra_disjoint_or32xi16:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.h, vl16
; VBITS_GE_256-NEXT:    mov x8, #16 // =0x10
; VBITS_GE_256-NEXT:    ld1h { z0.h }, p0/z, [x0, x8, lsl #1]
; VBITS_GE_256-NEXT:    ld1h { z1.h }, p0/z, [x1, x8, lsl #1]
; VBITS_GE_256-NEXT:    ld1h { z2.h }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1h { z3.h }, p0/z, [x1]
; VBITS_GE_256-NEXT:    ssra z0.h, z1.h, #4
; VBITS_GE_256-NEXT:    ssra z2.h, z3.h, #4
; VBITS_GE_256-NEXT:    st1h { z0.h }, p0, [x0, x8, lsl #1]
; VBITS_GE_256-NEXT:    st1h { z2.h }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: ssra_disjoint_or32xi16:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.h, vl32
; VBITS_GE_512-NEXT:    ld1h { z0.h }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1h { z1.h }, p0/z, [x1]
; VBITS_GE_512-NEXT:    ssra z0.h, z1.h, #4
; VBITS_GE_512-NEXT:    st1h { z0.h }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <32 x i16>, ptr %a
  %vb = load <32 x i16>, ptr %b
  %shift = ashr <32 x i16> %vb, splat(i16 4)
  %res = or disjoint <32 x i16> %va, %shift
  store <32 x i16> %res, ptr %a
  ret void
}

define void @ssra_disjoint_or64xi16(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: ssra_disjoint_or64xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl64
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    ld1h { z1.h }, p0/z, [x1]
; CHECK-NEXT:    ssra z0.h, z1.h, #4
; CHECK-NEXT:    st1h { z0.h }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <64 x i16>, ptr %a
  %vb = load <64 x i16>, ptr %b
  %shift = ashr <64 x i16> %vb, splat(i16 4)
  %res = or disjoint <64 x i16> %va, %shift
  store <64 x i16> %res, ptr %a
  ret void
}

define void @ssra_disjoint_or128xi16(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: ssra_disjoint_or128xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl128
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    ld1h { z1.h }, p0/z, [x1]
; CHECK-NEXT:    ssra z0.h, z1.h, #4
; CHECK-NEXT:    st1h { z0.h }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <128 x i16>, ptr %a
  %vb = load <128 x i16>, ptr %b
  %shift = ashr <128 x i16> %vb, splat(i16 4)
  %res = or disjoint <128 x i16> %va, %shift
  store <128 x i16> %res, ptr %a
  ret void
}

define <2 x i32> @ssra_disjoint_or2xi32(<2 x i32> %a, <2 x i32> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_or2xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ssra v0.2s, v1.2s, #4
; CHECK-NEXT:    ret
  %shift = ashr <2 x i32> %b, splat(i32 4)
  %res = or disjoint <2 x i32> %a, %shift
  ret <2 x i32> %res
}

define <4 x i32> @ssra_disjoint_or4xi32(<4 x i32> %a, <4 x i32> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_or4xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ssra v0.4s, v1.4s, #4
; CHECK-NEXT:    ret
  %shift = ashr <4 x i32> %b, splat(i32 4)
  %res = or disjoint <4 x i32> %a, %shift
  ret <4 x i32> %res
}

define void @ssra_disjoint_or8xi32(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_or8xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s, vl8
; CHECK-NEXT:    ld1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    ld1w { z1.s }, p0/z, [x1]
; CHECK-NEXT:    ssra z0.s, z1.s, #4
; CHECK-NEXT:    st1w { z0.s }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <8 x i32>, ptr %a
  %vb = load <8 x i32>, ptr %b
  %shift = ashr <8 x i32> %vb, splat(i32 4)
  %res = or disjoint <8 x i32> %va, %shift
  store <8 x i32> %res, ptr %a
  ret void
}

define void @ssra_disjoint_or16xi32(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: ssra_disjoint_or16xi32:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.s, vl8
; VBITS_GE_256-NEXT:    mov x8, #8 // =0x8
; VBITS_GE_256-NEXT:    ld1w { z0.s }, p0/z, [x0, x8, lsl #2]
; VBITS_GE_256-NEXT:    ld1w { z1.s }, p0/z, [x1, x8, lsl #2]
; VBITS_GE_256-NEXT:    ld1w { z2.s }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1w { z3.s }, p0/z, [x1]
; VBITS_GE_256-NEXT:    ssra z0.s, z1.s, #4
; VBITS_GE_256-NEXT:    ssra z2.s, z3.s, #4
; VBITS_GE_256-NEXT:    st1w { z0.s }, p0, [x0, x8, lsl #2]
; VBITS_GE_256-NEXT:    st1w { z2.s }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: ssra_disjoint_or16xi32:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.s, vl16
; VBITS_GE_512-NEXT:    ld1w { z0.s }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1w { z1.s }, p0/z, [x1]
; VBITS_GE_512-NEXT:    ssra z0.s, z1.s, #4
; VBITS_GE_512-NEXT:    st1w { z0.s }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <16 x i32>, ptr %a
  %vb = load <16 x i32>, ptr %b
  %shift = ashr <16 x i32> %vb, splat(i32 4)
  %res = or disjoint <16 x i32> %va, %shift
  store <16 x i32> %res, ptr %a
  ret void
}

define void @ssra_disjoint_or32xi32(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: ssra_disjoint_or32xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s, vl32
; CHECK-NEXT:    ld1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    ld1w { z1.s }, p0/z, [x1]
; CHECK-NEXT:    ssra z0.s, z1.s, #4
; CHECK-NEXT:    st1w { z0.s }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <32 x i32>, ptr %a
  %vb = load <32 x i32>, ptr %b
  %shift = ashr <32 x i32> %vb, splat(i32 4)
  %res = or disjoint <32 x i32> %va, %shift
  store <32 x i32> %res, ptr %a
  ret void
}

define void @ssra_disjoint_or64xi32(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: ssra_disjoint_or64xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s, vl64
; CHECK-NEXT:    ld1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    ld1w { z1.s }, p0/z, [x1]
; CHECK-NEXT:    ssra z0.s, z1.s, #4
; CHECK-NEXT:    st1w { z0.s }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <64 x i32>, ptr %a
  %vb = load <64 x i32>, ptr %b
  %shift = ashr <64 x i32> %vb, splat(i32 4)
  %res = or disjoint <64 x i32> %va, %shift
  store <64 x i32> %res, ptr %a
  ret void
}

define <1 x i64> @ssra_disjoint_or1xi64(<1 x i64> %a, <1 x i64> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_or1xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ssra d0, d1, #4
; CHECK-NEXT:    ret
  %shift = ashr <1 x i64> %b, splat(i64 4)
  %res = or disjoint <1 x i64> %a, %shift
  ret <1 x i64> %res
}

define <2 x i64> @ssra_disjoint_or2xi64(<2 x i64> %a, <2 x i64> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_or2xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ssra v0.2d, v1.2d, #4
; CHECK-NEXT:    ret
  %shift = ashr <2 x i64> %b, splat(i64 4)
  %res = or disjoint <2 x i64> %a, %shift
  ret <2 x i64> %res
}

define void @ssra_disjoint_or4xi64(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_or4xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d, vl4
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    ld1d { z1.d }, p0/z, [x1]
; CHECK-NEXT:    ssra z0.d, z1.d, #4
; CHECK-NEXT:    st1d { z0.d }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <4 x i64>, ptr %a
  %vb = load <4 x i64>, ptr %b
  %shift = ashr <4 x i64> %vb, splat(i64 4)
  %res = or disjoint <4 x i64> %va, %shift
  store <4 x i64> %res, ptr %a
  ret void
}

define void @ssra_disjoint_or8xi64(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: ssra_disjoint_or8xi64:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.d, vl4
; VBITS_GE_256-NEXT:    mov x8, #4 // =0x4
; VBITS_GE_256-NEXT:    ld1d { z0.d }, p0/z, [x0, x8, lsl #3]
; VBITS_GE_256-NEXT:    ld1d { z1.d }, p0/z, [x1, x8, lsl #3]
; VBITS_GE_256-NEXT:    ld1d { z2.d }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1d { z3.d }, p0/z, [x1]
; VBITS_GE_256-NEXT:    ssra z0.d, z1.d, #4
; VBITS_GE_256-NEXT:    ssra z2.d, z3.d, #4
; VBITS_GE_256-NEXT:    st1d { z0.d }, p0, [x0, x8, lsl #3]
; VBITS_GE_256-NEXT:    st1d { z2.d }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: ssra_disjoint_or8xi64:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.d, vl8
; VBITS_GE_512-NEXT:    ld1d { z0.d }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1d { z1.d }, p0/z, [x1]
; VBITS_GE_512-NEXT:    ssra z0.d, z1.d, #4
; VBITS_GE_512-NEXT:    st1d { z0.d }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <8 x i64>, ptr %a
  %vb = load <8 x i64>, ptr %b
  %shift = ashr <8 x i64> %vb, splat(i64 4)
  %res = or disjoint <8 x i64> %va, %shift
  store <8 x i64> %res, ptr %a
  ret void
}

define void @ssra_disjoint_or16xi64(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: ssra_disjoint_or16xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d, vl16
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    ld1d { z1.d }, p0/z, [x1]
; CHECK-NEXT:    ssra z0.d, z1.d, #4
; CHECK-NEXT:    st1d { z0.d }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <16 x i64>, ptr %a
  %vb = load <16 x i64>, ptr %b
  %shift = ashr <16 x i64> %vb, splat(i64 4)
  %res = or disjoint <16 x i64> %va, %shift
  store <16 x i64> %res, ptr %a
  ret void
}

define void @ssra_disjoint_or32xi64(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: ssra_disjoint_or32xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d, vl32
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    ld1d { z1.d }, p0/z, [x1]
; CHECK-NEXT:    ssra z0.d, z1.d, #4
; CHECK-NEXT:    st1d { z0.d }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <32 x i64>, ptr %a
  %vb = load <32 x i64>, ptr %b
  %shift = ashr <32 x i64> %vb, splat(i64 4)
  %res = or disjoint <32 x i64> %va, %shift
  store <32 x i64> %res, ptr %a
  ret void
}

;
; USRA disjoint shifted OR
;

define <8 x i8> @usra_disjoint_shift_or8xi8(<8 x i8> %a, <8 x i8> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or8xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    shl v0.8b, v0.8b, #7
; CHECK-NEXT:    usra v0.8b, v1.8b, #1
; CHECK-NEXT:    ret
  %shl = shl <8 x i8> %a, splat(i8 7)
  %srl = lshr <8 x i8> %b, splat(i8 1)
  %res = or <8 x i8> %shl, %srl
  ret <8 x i8> %res
}

define <16 x i8> @usra_disjoint_shift_or16xi8(<16 x i8> %a, <16 x i8> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or16xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    shl v0.16b, v0.16b, #7
; CHECK-NEXT:    usra v0.16b, v1.16b, #1
; CHECK-NEXT:    ret
  %shl = shl <16 x i8> %a, splat(i8 7)
  %srl = lshr <16 x i8> %b, splat(i8 1)
  %res = or <16 x i8> %shl, %srl
  ret <16 x i8> %res
}

define void @usra_disjoint_shift_or32xi8(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or32xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl32
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1]
; CHECK-NEXT:    lsl z0.b, z0.b, #7
; CHECK-NEXT:    usra z0.b, z1.b, #1
; CHECK-NEXT:    st1b { z0.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <32 x i8>, ptr %a
  %vb = load <32 x i8>, ptr %b
  %shl = shl <32 x i8> %va, splat(i8 7)
  %srl = lshr <32 x i8> %vb, splat(i8 1)
  %res = or <32 x i8> %shl, %srl
  store <32 x i8> %res, ptr %a
  ret void
}

define void @usra_disjoint_shift_or64xi8(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: usra_disjoint_shift_or64xi8:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.b, vl32
; VBITS_GE_256-NEXT:    mov w8, #32 // =0x20
; VBITS_GE_256-NEXT:    ld1b { z0.b }, p0/z, [x0, x8]
; VBITS_GE_256-NEXT:    ld1b { z1.b }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1b { z2.b }, p0/z, [x1, x8]
; VBITS_GE_256-NEXT:    ld1b { z3.b }, p0/z, [x1]
; VBITS_GE_256-NEXT:    lsl z0.b, z0.b, #7
; VBITS_GE_256-NEXT:    lsl z1.b, z1.b, #7
; VBITS_GE_256-NEXT:    usra z0.b, z2.b, #1
; VBITS_GE_256-NEXT:    usra z1.b, z3.b, #1
; VBITS_GE_256-NEXT:    st1b { z0.b }, p0, [x0, x8]
; VBITS_GE_256-NEXT:    st1b { z1.b }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: usra_disjoint_shift_or64xi8:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.b, vl64
; VBITS_GE_512-NEXT:    ld1b { z0.b }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1b { z1.b }, p0/z, [x1]
; VBITS_GE_512-NEXT:    lsl z0.b, z0.b, #7
; VBITS_GE_512-NEXT:    usra z0.b, z1.b, #1
; VBITS_GE_512-NEXT:    st1b { z0.b }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <64 x i8>, ptr %a
  %vb = load <64 x i8>, ptr %b
  %shl = shl <64 x i8> %va, splat(i8 7)
  %srl = lshr <64 x i8> %vb, splat(i8 1)
  %res = or <64 x i8> %shl, %srl
  store <64 x i8> %res, ptr %a
  ret void
}

define void @usra_disjoint_shift_or128xi8(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or128xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl128
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1]
; CHECK-NEXT:    lsl z0.b, z0.b, #7
; CHECK-NEXT:    usra z0.b, z1.b, #1
; CHECK-NEXT:    st1b { z0.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <128 x i8>, ptr %a
  %vb = load <128 x i8>, ptr %b
  %shl = shl <128 x i8> %va, splat(i8 7)
  %srl = lshr <128 x i8> %vb, splat(i8 1)
  %res = or <128 x i8> %shl, %srl
  store <128 x i8> %res, ptr %a
  ret void
}

define void @usra_disjoint_shift_or256xi8(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or256xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl256
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1]
; CHECK-NEXT:    lsl z0.b, z0.b, #7
; CHECK-NEXT:    usra z0.b, z1.b, #1
; CHECK-NEXT:    st1b { z0.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <256 x i8>, ptr %a
  %vb = load <256 x i8>, ptr %b
  %shl = shl <256 x i8> %va, splat(i8 7)
  %srl = lshr <256 x i8> %vb, splat(i8 1)
  %res = or <256 x i8> %shl, %srl
  store <256 x i8> %res, ptr %a
  ret void
}

define <4 x i16> @usra_disjoint_shift_or4xi16(<4 x i16> %a, <4 x i16> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or4xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    shl v0.4h, v0.4h, #7
; CHECK-NEXT:    usra v0.4h, v1.4h, #9
; CHECK-NEXT:    ret
  %shl = shl <4 x i16> %a, splat(i16 7)
  %srl = lshr <4 x i16> %b, splat(i16 9)
  %res = or <4 x i16> %shl, %srl
  ret <4 x i16> %res
}

define <8 x i16> @usra_disjoint_shift_or8xi16(<8 x i16> %a, <8 x i16> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or8xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    shl v0.8h, v0.8h, #7
; CHECK-NEXT:    usra v0.8h, v1.8h, #9
; CHECK-NEXT:    ret
  %shl = shl <8 x i16> %a, splat(i16 7)
  %srl = lshr <8 x i16> %b, splat(i16 9)
  %res = or <8 x i16> %shl, %srl
  ret <8 x i16> %res
}

define void @usra_disjoint_shift_or16xi16(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or16xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl16
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    ld1h { z1.h }, p0/z, [x1]
; CHECK-NEXT:    lsl z0.h, z0.h, #7
; CHECK-NEXT:    usra z0.h, z1.h, #9
; CHECK-NEXT:    st1h { z0.h }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <16 x i16>, ptr %a
  %vb = load <16 x i16>, ptr %b
  %shl = shl <16 x i16> %va, splat(i16 7)
  %srl = lshr <16 x i16> %vb, splat(i16 9)
  %res = or <16 x i16> %shl, %srl
  store <16 x i16> %res, ptr %a
  ret void
}

define void @usra_disjoint_shift_or32xi16(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: usra_disjoint_shift_or32xi16:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.h, vl16
; VBITS_GE_256-NEXT:    mov x8, #16 // =0x10
; VBITS_GE_256-NEXT:    ld1h { z0.h }, p0/z, [x0, x8, lsl #1]
; VBITS_GE_256-NEXT:    ld1h { z1.h }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1h { z2.h }, p0/z, [x1, x8, lsl #1]
; VBITS_GE_256-NEXT:    ld1h { z3.h }, p0/z, [x1]
; VBITS_GE_256-NEXT:    lsl z0.h, z0.h, #7
; VBITS_GE_256-NEXT:    lsl z1.h, z1.h, #7
; VBITS_GE_256-NEXT:    usra z0.h, z2.h, #9
; VBITS_GE_256-NEXT:    usra z1.h, z3.h, #9
; VBITS_GE_256-NEXT:    st1h { z0.h }, p0, [x0, x8, lsl #1]
; VBITS_GE_256-NEXT:    st1h { z1.h }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: usra_disjoint_shift_or32xi16:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.h, vl32
; VBITS_GE_512-NEXT:    ld1h { z0.h }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1h { z1.h }, p0/z, [x1]
; VBITS_GE_512-NEXT:    lsl z0.h, z0.h, #7
; VBITS_GE_512-NEXT:    usra z0.h, z1.h, #9
; VBITS_GE_512-NEXT:    st1h { z0.h }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <32 x i16>, ptr %a
  %vb = load <32 x i16>, ptr %b
  %shl = shl <32 x i16> %va, splat(i16 7)
  %srl = lshr <32 x i16> %vb, splat(i16 9)
  %res = or <32 x i16> %shl, %srl
  store <32 x i16> %res, ptr %a
  ret void
}

define void @usra_disjoint_shift_or64xi16(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or64xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl64
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    ld1h { z1.h }, p0/z, [x1]
; CHECK-NEXT:    lsl z0.h, z0.h, #7
; CHECK-NEXT:    usra z0.h, z1.h, #9
; CHECK-NEXT:    st1h { z0.h }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <64 x i16>, ptr %a
  %vb = load <64 x i16>, ptr %b
  %shl = shl <64 x i16> %va, splat(i16 7)
  %srl = lshr <64 x i16> %vb, splat(i16 9)
  %res = or <64 x i16> %shl, %srl
  store <64 x i16> %res, ptr %a
  ret void
}

define void @usra_disjoint_shift_or128xi16(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or128xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl128
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    ld1h { z1.h }, p0/z, [x1]
; CHECK-NEXT:    lsl z0.h, z0.h, #7
; CHECK-NEXT:    usra z0.h, z1.h, #9
; CHECK-NEXT:    st1h { z0.h }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <128 x i16>, ptr %a
  %vb = load <128 x i16>, ptr %b
  %shl = shl <128 x i16> %va, splat(i16 7)
  %srl = lshr <128 x i16> %vb, splat(i16 9)
  %res = or <128 x i16> %shl, %srl
  store <128 x i16> %res, ptr %a
  ret void
}

define <2 x i32> @usra_disjoint_shift_or2xi32(<2 x i32> %a, <2 x i32> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or2xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    shl v0.2s, v0.2s, #7
; CHECK-NEXT:    usra v0.2s, v1.2s, #25
; CHECK-NEXT:    ret
  %shl = shl <2 x i32> %a, splat(i32 7)
  %srl = lshr <2 x i32> %b, splat(i32 25)
  %res = or <2 x i32> %shl, %srl
  ret <2 x i32> %res
}

define <4 x i32> @usra_disjoint_shift_or4xi32(<4 x i32> %a, <4 x i32> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or4xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    shl v0.4s, v0.4s, #7
; CHECK-NEXT:    usra v0.4s, v1.4s, #25
; CHECK-NEXT:    ret
  %shl = shl <4 x i32> %a, splat(i32 7)
  %srl = lshr <4 x i32> %b, splat(i32 25)
  %res = or <4 x i32> %shl, %srl
  ret <4 x i32> %res
}

define void @usra_disjoint_shift_or8xi32(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or8xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s, vl8
; CHECK-NEXT:    ld1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    ld1w { z1.s }, p0/z, [x1]
; CHECK-NEXT:    lsl z0.s, z0.s, #7
; CHECK-NEXT:    usra z0.s, z1.s, #25
; CHECK-NEXT:    st1w { z0.s }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <8 x i32>, ptr %a
  %vb = load <8 x i32>, ptr %b
  %shl = shl <8 x i32> %va, splat(i32 7)
  %srl = lshr <8 x i32> %vb, splat(i32 25)
  %res = or <8 x i32> %shl, %srl
  store <8 x i32> %res, ptr %a
  ret void
}

define void @usra_disjoint_shift_or16xi32(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: usra_disjoint_shift_or16xi32:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.s, vl8
; VBITS_GE_256-NEXT:    mov x8, #8 // =0x8
; VBITS_GE_256-NEXT:    ld1w { z0.s }, p0/z, [x0, x8, lsl #2]
; VBITS_GE_256-NEXT:    ld1w { z1.s }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1w { z2.s }, p0/z, [x1, x8, lsl #2]
; VBITS_GE_256-NEXT:    ld1w { z3.s }, p0/z, [x1]
; VBITS_GE_256-NEXT:    lsl z0.s, z0.s, #7
; VBITS_GE_256-NEXT:    lsl z1.s, z1.s, #7
; VBITS_GE_256-NEXT:    usra z0.s, z2.s, #25
; VBITS_GE_256-NEXT:    usra z1.s, z3.s, #25
; VBITS_GE_256-NEXT:    st1w { z0.s }, p0, [x0, x8, lsl #2]
; VBITS_GE_256-NEXT:    st1w { z1.s }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: usra_disjoint_shift_or16xi32:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.s, vl16
; VBITS_GE_512-NEXT:    ld1w { z0.s }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1w { z1.s }, p0/z, [x1]
; VBITS_GE_512-NEXT:    lsl z0.s, z0.s, #7
; VBITS_GE_512-NEXT:    usra z0.s, z1.s, #25
; VBITS_GE_512-NEXT:    st1w { z0.s }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <16 x i32>, ptr %a
  %vb = load <16 x i32>, ptr %b
  %shl = shl <16 x i32> %va, splat(i32 7)
  %srl = lshr <16 x i32> %vb, splat(i32 25)
  %res = or <16 x i32> %shl, %srl
  store <16 x i32> %res, ptr %a
  ret void
}

define void @usra_disjoint_shift_or32xi32(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or32xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s, vl32
; CHECK-NEXT:    ld1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    ld1w { z1.s }, p0/z, [x1]
; CHECK-NEXT:    lsl z0.s, z0.s, #7
; CHECK-NEXT:    usra z0.s, z1.s, #25
; CHECK-NEXT:    st1w { z0.s }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <32 x i32>, ptr %a
  %vb = load <32 x i32>, ptr %b
  %shl = shl <32 x i32> %va, splat(i32 7)
  %srl = lshr <32 x i32> %vb, splat(i32 25)
  %res = or <32 x i32> %shl, %srl
  store <32 x i32> %res, ptr %a
  ret void
}

define void @usra_disjoint_shift_or64xi32(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or64xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s, vl64
; CHECK-NEXT:    ld1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    ld1w { z1.s }, p0/z, [x1]
; CHECK-NEXT:    lsl z0.s, z0.s, #7
; CHECK-NEXT:    usra z0.s, z1.s, #25
; CHECK-NEXT:    st1w { z0.s }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <64 x i32>, ptr %a
  %vb = load <64 x i32>, ptr %b
  %shl = shl <64 x i32> %va, splat(i32 7)
  %srl = lshr <64 x i32> %vb, splat(i32 25)
  %res = or <64 x i32> %shl, %srl
  store <64 x i32> %res, ptr %a
  ret void
}

define <1 x i64> @usra_disjoint_shift_or1xi64(<1 x i64> %a, <1 x i64> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or1xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    shl d0, d0, #7
; CHECK-NEXT:    usra d0, d1, #57
; CHECK-NEXT:    ret
  %shl = shl <1 x i64> %a, splat(i64 7)
  %srl = lshr <1 x i64> %b, splat(i64 57)
  %res = or <1 x i64> %shl, %srl
  ret <1 x i64> %res
}

define <2 x i64> @usra_disjoint_shift_or2xi64(<2 x i64> %a, <2 x i64> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or2xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    shl v0.2d, v0.2d, #7
; CHECK-NEXT:    usra v0.2d, v1.2d, #57
; CHECK-NEXT:    ret
  %shl = shl <2 x i64> %a, splat(i64 7)
  %srl = lshr <2 x i64> %b, splat(i64 57)
  %res = or <2 x i64> %shl, %srl
  ret <2 x i64> %res
}

define void @usra_disjoint_shift_or4xi64(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or4xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d, vl4
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    ld1d { z1.d }, p0/z, [x1]
; CHECK-NEXT:    lsl z0.d, z0.d, #7
; CHECK-NEXT:    usra z0.d, z1.d, #57
; CHECK-NEXT:    st1d { z0.d }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <4 x i64>, ptr %a
  %vb = load <4 x i64>, ptr %b
  %shl = shl <4 x i64> %va, splat(i64 7)
  %srl = lshr <4 x i64> %vb, splat(i64 57)
  %res = or <4 x i64> %shl, %srl
  store <4 x i64> %res, ptr %a
  ret void
}

define void @usra_disjoint_shift_or8xi64(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: usra_disjoint_shift_or8xi64:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.d, vl4
; VBITS_GE_256-NEXT:    mov x8, #4 // =0x4
; VBITS_GE_256-NEXT:    ld1d { z0.d }, p0/z, [x0, x8, lsl #3]
; VBITS_GE_256-NEXT:    ld1d { z1.d }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1d { z2.d }, p0/z, [x1, x8, lsl #3]
; VBITS_GE_256-NEXT:    ld1d { z3.d }, p0/z, [x1]
; VBITS_GE_256-NEXT:    lsl z0.d, z0.d, #7
; VBITS_GE_256-NEXT:    lsl z1.d, z1.d, #7
; VBITS_GE_256-NEXT:    usra z0.d, z2.d, #57
; VBITS_GE_256-NEXT:    usra z1.d, z3.d, #57
; VBITS_GE_256-NEXT:    st1d { z0.d }, p0, [x0, x8, lsl #3]
; VBITS_GE_256-NEXT:    st1d { z1.d }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: usra_disjoint_shift_or8xi64:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.d, vl8
; VBITS_GE_512-NEXT:    ld1d { z0.d }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1d { z1.d }, p0/z, [x1]
; VBITS_GE_512-NEXT:    lsl z0.d, z0.d, #7
; VBITS_GE_512-NEXT:    usra z0.d, z1.d, #57
; VBITS_GE_512-NEXT:    st1d { z0.d }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <8 x i64>, ptr %a
  %vb = load <8 x i64>, ptr %b
  %shl = shl <8 x i64> %va, splat(i64 7)
  %srl = lshr <8 x i64> %vb, splat(i64 57)
  %res = or <8 x i64> %shl, %srl
  store <8 x i64> %res, ptr %a
  ret void
}

define void @usra_disjoint_shift_or16xi64(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or16xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d, vl16
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    ld1d { z1.d }, p0/z, [x1]
; CHECK-NEXT:    lsl z0.d, z0.d, #7
; CHECK-NEXT:    usra z0.d, z1.d, #57
; CHECK-NEXT:    st1d { z0.d }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <16 x i64>, ptr %a
  %vb = load <16 x i64>, ptr %b
  %shl = shl <16 x i64> %va, splat(i64 7)
  %srl = lshr <16 x i64> %vb, splat(i64 57)
  %res = or <16 x i64> %shl, %srl
  store <16 x i64> %res, ptr %a
  ret void
}

define void @usra_disjoint_shift_or32xi64(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: usra_disjoint_shift_or32xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d, vl32
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    ld1d { z1.d }, p0/z, [x1]
; CHECK-NEXT:    lsl z0.d, z0.d, #7
; CHECK-NEXT:    usra z0.d, z1.d, #57
; CHECK-NEXT:    st1d { z0.d }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <32 x i64>, ptr %a
  %vb = load <32 x i64>, ptr %b
  %shl = shl <32 x i64> %va, splat(i64 7)
  %srl = lshr <32 x i64> %vb, splat(i64 57)
  %res = or <32 x i64> %shl, %srl
  store <32 x i64> %res, ptr %a
  ret void
}

;
; SSRA disjoint shifted OR
;

define <8 x i8> @ssra_disjoint_shift_or8xi8(<8 x i8> %a, <8 x i8> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or8xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ushr v0.8b, v0.8b, #2
; CHECK-NEXT:    shl v1.8b, v1.8b, #7
; CHECK-NEXT:    ssra v0.8b, v1.8b, #1
; CHECK-NEXT:    ret
  %acc = lshr <8 x i8> %a, splat(i8 2)
  %sign = shl <8 x i8> %b, splat(i8 7)
  %sra = ashr <8 x i8> %sign, splat(i8 1)
  %res = or <8 x i8> %acc, %sra
  ret <8 x i8> %res
}

define <16 x i8> @ssra_disjoint_shift_or16xi8(<16 x i8> %a, <16 x i8> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or16xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ushr v0.16b, v0.16b, #2
; CHECK-NEXT:    shl v1.16b, v1.16b, #7
; CHECK-NEXT:    ssra v0.16b, v1.16b, #1
; CHECK-NEXT:    ret
  %acc = lshr <16 x i8> %a, splat(i8 2)
  %sign = shl <16 x i8> %b, splat(i8 7)
  %sra = ashr <16 x i8> %sign, splat(i8 1)
  %res = or <16 x i8> %acc, %sra
  ret <16 x i8> %res
}

define void @ssra_disjoint_shift_or32xi8(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or32xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl32
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1]
; CHECK-NEXT:    lsr z0.b, z0.b, #2
; CHECK-NEXT:    lsl z1.b, z1.b, #7
; CHECK-NEXT:    ssra z0.b, z1.b, #1
; CHECK-NEXT:    st1b { z0.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <32 x i8>, ptr %a
  %vb = load <32 x i8>, ptr %b
  %acc = lshr <32 x i8> %va, splat(i8 2)
  %sign = shl <32 x i8> %vb, splat(i8 7)
  %sra = ashr <32 x i8> %sign, splat(i8 1)
  %res = or <32 x i8> %acc, %sra
  store <32 x i8> %res, ptr %a
  ret void
}

define void @ssra_disjoint_shift_or64xi8(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: ssra_disjoint_shift_or64xi8:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.b, vl32
; VBITS_GE_256-NEXT:    mov w8, #32 // =0x20
; VBITS_GE_256-NEXT:    ld1b { z0.b }, p0/z, [x0, x8]
; VBITS_GE_256-NEXT:    ld1b { z1.b }, p0/z, [x1, x8]
; VBITS_GE_256-NEXT:    ld1b { z2.b }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1b { z3.b }, p0/z, [x1]
; VBITS_GE_256-NEXT:    lsr z0.b, z0.b, #2
; VBITS_GE_256-NEXT:    lsl z1.b, z1.b, #7
; VBITS_GE_256-NEXT:    lsr z2.b, z2.b, #2
; VBITS_GE_256-NEXT:    lsl z3.b, z3.b, #7
; VBITS_GE_256-NEXT:    ssra z0.b, z1.b, #1
; VBITS_GE_256-NEXT:    ssra z2.b, z3.b, #1
; VBITS_GE_256-NEXT:    st1b { z0.b }, p0, [x0, x8]
; VBITS_GE_256-NEXT:    st1b { z2.b }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: ssra_disjoint_shift_or64xi8:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.b, vl64
; VBITS_GE_512-NEXT:    ld1b { z0.b }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1b { z1.b }, p0/z, [x1]
; VBITS_GE_512-NEXT:    lsr z0.b, z0.b, #2
; VBITS_GE_512-NEXT:    lsl z1.b, z1.b, #7
; VBITS_GE_512-NEXT:    ssra z0.b, z1.b, #1
; VBITS_GE_512-NEXT:    st1b { z0.b }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <64 x i8>, ptr %a
  %vb = load <64 x i8>, ptr %b
  %acc = lshr <64 x i8> %va, splat(i8 2)
  %sign = shl <64 x i8> %vb, splat(i8 7)
  %sra = ashr <64 x i8> %sign, splat(i8 1)
  %res = or <64 x i8> %acc, %sra
  store <64 x i8> %res, ptr %a
  ret void
}

define void @ssra_disjoint_shift_or128xi8(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or128xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl128
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1]
; CHECK-NEXT:    lsr z0.b, z0.b, #2
; CHECK-NEXT:    lsl z1.b, z1.b, #7
; CHECK-NEXT:    ssra z0.b, z1.b, #1
; CHECK-NEXT:    st1b { z0.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <128 x i8>, ptr %a
  %vb = load <128 x i8>, ptr %b
  %acc = lshr <128 x i8> %va, splat(i8 2)
  %sign = shl <128 x i8> %vb, splat(i8 7)
  %sra = ashr <128 x i8> %sign, splat(i8 1)
  %res = or <128 x i8> %acc, %sra
  store <128 x i8> %res, ptr %a
  ret void
}

define void @ssra_disjoint_shift_or256xi8(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or256xi8:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.b, vl256
; CHECK-NEXT:    ld1b { z0.b }, p0/z, [x0]
; CHECK-NEXT:    ld1b { z1.b }, p0/z, [x1]
; CHECK-NEXT:    lsr z0.b, z0.b, #2
; CHECK-NEXT:    lsl z1.b, z1.b, #7
; CHECK-NEXT:    ssra z0.b, z1.b, #1
; CHECK-NEXT:    st1b { z0.b }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <256 x i8>, ptr %a
  %vb = load <256 x i8>, ptr %b
  %acc = lshr <256 x i8> %va, splat(i8 2)
  %sign = shl <256 x i8> %vb, splat(i8 7)
  %sra = ashr <256 x i8> %sign, splat(i8 1)
  %res = or <256 x i8> %acc, %sra
  store <256 x i8> %res, ptr %a
  ret void
}

define <4 x i16> @ssra_disjoint_shift_or4xi16(<4 x i16> %a, <4 x i16> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or4xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ushr v0.4h, v0.4h, #10
; CHECK-NEXT:    shl v1.4h, v1.4h, #15
; CHECK-NEXT:    ssra v0.4h, v1.4h, #9
; CHECK-NEXT:    ret
  %acc = lshr <4 x i16> %a, splat(i16 10)
  %sign = shl <4 x i16> %b, splat(i16 15)
  %sra = ashr <4 x i16> %sign, splat(i16 9)
  %res = or <4 x i16> %acc, %sra
  ret <4 x i16> %res
}

define <8 x i16> @ssra_disjoint_shift_or8xi16(<8 x i16> %a, <8 x i16> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or8xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ushr v0.8h, v0.8h, #10
; CHECK-NEXT:    shl v1.8h, v1.8h, #15
; CHECK-NEXT:    ssra v0.8h, v1.8h, #9
; CHECK-NEXT:    ret
  %acc = lshr <8 x i16> %a, splat(i16 10)
  %sign = shl <8 x i16> %b, splat(i16 15)
  %sra = ashr <8 x i16> %sign, splat(i16 9)
  %res = or <8 x i16> %acc, %sra
  ret <8 x i16> %res
}

define void @ssra_disjoint_shift_or16xi16(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or16xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl16
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    ld1h { z1.h }, p0/z, [x1]
; CHECK-NEXT:    lsr z0.h, z0.h, #10
; CHECK-NEXT:    lsl z1.h, z1.h, #15
; CHECK-NEXT:    ssra z0.h, z1.h, #9
; CHECK-NEXT:    st1h { z0.h }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <16 x i16>, ptr %a
  %vb = load <16 x i16>, ptr %b
  %acc = lshr <16 x i16> %va, splat(i16 10)
  %sign = shl <16 x i16> %vb, splat(i16 15)
  %sra = ashr <16 x i16> %sign, splat(i16 9)
  %res = or <16 x i16> %acc, %sra
  store <16 x i16> %res, ptr %a
  ret void
}

define void @ssra_disjoint_shift_or32xi16(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: ssra_disjoint_shift_or32xi16:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.h, vl16
; VBITS_GE_256-NEXT:    mov x8, #16 // =0x10
; VBITS_GE_256-NEXT:    ld1h { z0.h }, p0/z, [x0, x8, lsl #1]
; VBITS_GE_256-NEXT:    ld1h { z1.h }, p0/z, [x1, x8, lsl #1]
; VBITS_GE_256-NEXT:    ld1h { z2.h }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1h { z3.h }, p0/z, [x1]
; VBITS_GE_256-NEXT:    lsr z0.h, z0.h, #10
; VBITS_GE_256-NEXT:    lsl z1.h, z1.h, #15
; VBITS_GE_256-NEXT:    lsr z2.h, z2.h, #10
; VBITS_GE_256-NEXT:    lsl z3.h, z3.h, #15
; VBITS_GE_256-NEXT:    ssra z0.h, z1.h, #9
; VBITS_GE_256-NEXT:    ssra z2.h, z3.h, #9
; VBITS_GE_256-NEXT:    st1h { z0.h }, p0, [x0, x8, lsl #1]
; VBITS_GE_256-NEXT:    st1h { z2.h }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: ssra_disjoint_shift_or32xi16:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.h, vl32
; VBITS_GE_512-NEXT:    ld1h { z0.h }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1h { z1.h }, p0/z, [x1]
; VBITS_GE_512-NEXT:    lsr z0.h, z0.h, #10
; VBITS_GE_512-NEXT:    lsl z1.h, z1.h, #15
; VBITS_GE_512-NEXT:    ssra z0.h, z1.h, #9
; VBITS_GE_512-NEXT:    st1h { z0.h }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <32 x i16>, ptr %a
  %vb = load <32 x i16>, ptr %b
  %acc = lshr <32 x i16> %va, splat(i16 10)
  %sign = shl <32 x i16> %vb, splat(i16 15)
  %sra = ashr <32 x i16> %sign, splat(i16 9)
  %res = or <32 x i16> %acc, %sra
  store <32 x i16> %res, ptr %a
  ret void
}

define void @ssra_disjoint_shift_or64xi16(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or64xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl64
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    ld1h { z1.h }, p0/z, [x1]
; CHECK-NEXT:    lsr z0.h, z0.h, #10
; CHECK-NEXT:    lsl z1.h, z1.h, #15
; CHECK-NEXT:    ssra z0.h, z1.h, #9
; CHECK-NEXT:    st1h { z0.h }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <64 x i16>, ptr %a
  %vb = load <64 x i16>, ptr %b
  %acc = lshr <64 x i16> %va, splat(i16 10)
  %sign = shl <64 x i16> %vb, splat(i16 15)
  %sra = ashr <64 x i16> %sign, splat(i16 9)
  %res = or <64 x i16> %acc, %sra
  store <64 x i16> %res, ptr %a
  ret void
}

define void @ssra_disjoint_shift_or128xi16(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or128xi16:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.h, vl128
; CHECK-NEXT:    ld1h { z0.h }, p0/z, [x0]
; CHECK-NEXT:    ld1h { z1.h }, p0/z, [x1]
; CHECK-NEXT:    lsr z0.h, z0.h, #10
; CHECK-NEXT:    lsl z1.h, z1.h, #15
; CHECK-NEXT:    ssra z0.h, z1.h, #9
; CHECK-NEXT:    st1h { z0.h }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <128 x i16>, ptr %a
  %vb = load <128 x i16>, ptr %b
  %acc = lshr <128 x i16> %va, splat(i16 10)
  %sign = shl <128 x i16> %vb, splat(i16 15)
  %sra = ashr <128 x i16> %sign, splat(i16 9)
  %res = or <128 x i16> %acc, %sra
  store <128 x i16> %res, ptr %a
  ret void
}

define <2 x i32> @ssra_disjoint_shift_or2xi32(<2 x i32> %a, <2 x i32> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or2xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ushr v0.2s, v0.2s, #26
; CHECK-NEXT:    shl v1.2s, v1.2s, #31
; CHECK-NEXT:    ssra v0.2s, v1.2s, #25
; CHECK-NEXT:    ret
  %acc = lshr <2 x i32> %a, splat(i32 26)
  %sign = shl <2 x i32> %b, splat(i32 31)
  %sra = ashr <2 x i32> %sign, splat(i32 25)
  %res = or <2 x i32> %acc, %sra
  ret <2 x i32> %res
}

define <4 x i32> @ssra_disjoint_shift_or4xi32(<4 x i32> %a, <4 x i32> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or4xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ushr v0.4s, v0.4s, #26
; CHECK-NEXT:    shl v1.4s, v1.4s, #31
; CHECK-NEXT:    ssra v0.4s, v1.4s, #25
; CHECK-NEXT:    ret
  %acc = lshr <4 x i32> %a, splat(i32 26)
  %sign = shl <4 x i32> %b, splat(i32 31)
  %sra = ashr <4 x i32> %sign, splat(i32 25)
  %res = or <4 x i32> %acc, %sra
  ret <4 x i32> %res
}

define void @ssra_disjoint_shift_or8xi32(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or8xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s, vl8
; CHECK-NEXT:    ld1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    ld1w { z1.s }, p0/z, [x1]
; CHECK-NEXT:    lsr z0.s, z0.s, #26
; CHECK-NEXT:    lsl z1.s, z1.s, #31
; CHECK-NEXT:    ssra z0.s, z1.s, #25
; CHECK-NEXT:    st1w { z0.s }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <8 x i32>, ptr %a
  %vb = load <8 x i32>, ptr %b
  %acc = lshr <8 x i32> %va, splat(i32 26)
  %sign = shl <8 x i32> %vb, splat(i32 31)
  %sra = ashr <8 x i32> %sign, splat(i32 25)
  %res = or <8 x i32> %acc, %sra
  store <8 x i32> %res, ptr %a
  ret void
}

define void @ssra_disjoint_shift_or16xi32(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: ssra_disjoint_shift_or16xi32:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.s, vl8
; VBITS_GE_256-NEXT:    mov x8, #8 // =0x8
; VBITS_GE_256-NEXT:    ld1w { z0.s }, p0/z, [x0, x8, lsl #2]
; VBITS_GE_256-NEXT:    ld1w { z1.s }, p0/z, [x1, x8, lsl #2]
; VBITS_GE_256-NEXT:    ld1w { z2.s }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1w { z3.s }, p0/z, [x1]
; VBITS_GE_256-NEXT:    lsr z0.s, z0.s, #26
; VBITS_GE_256-NEXT:    lsl z1.s, z1.s, #31
; VBITS_GE_256-NEXT:    lsr z2.s, z2.s, #26
; VBITS_GE_256-NEXT:    lsl z3.s, z3.s, #31
; VBITS_GE_256-NEXT:    ssra z0.s, z1.s, #25
; VBITS_GE_256-NEXT:    ssra z2.s, z3.s, #25
; VBITS_GE_256-NEXT:    st1w { z0.s }, p0, [x0, x8, lsl #2]
; VBITS_GE_256-NEXT:    st1w { z2.s }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: ssra_disjoint_shift_or16xi32:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.s, vl16
; VBITS_GE_512-NEXT:    ld1w { z0.s }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1w { z1.s }, p0/z, [x1]
; VBITS_GE_512-NEXT:    lsr z0.s, z0.s, #26
; VBITS_GE_512-NEXT:    lsl z1.s, z1.s, #31
; VBITS_GE_512-NEXT:    ssra z0.s, z1.s, #25
; VBITS_GE_512-NEXT:    st1w { z0.s }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <16 x i32>, ptr %a
  %vb = load <16 x i32>, ptr %b
  %acc = lshr <16 x i32> %va, splat(i32 26)
  %sign = shl <16 x i32> %vb, splat(i32 31)
  %sra = ashr <16 x i32> %sign, splat(i32 25)
  %res = or <16 x i32> %acc, %sra
  store <16 x i32> %res, ptr %a
  ret void
}

define void @ssra_disjoint_shift_or32xi32(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or32xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s, vl32
; CHECK-NEXT:    ld1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    ld1w { z1.s }, p0/z, [x1]
; CHECK-NEXT:    lsr z0.s, z0.s, #26
; CHECK-NEXT:    lsl z1.s, z1.s, #31
; CHECK-NEXT:    ssra z0.s, z1.s, #25
; CHECK-NEXT:    st1w { z0.s }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <32 x i32>, ptr %a
  %vb = load <32 x i32>, ptr %b
  %acc = lshr <32 x i32> %va, splat(i32 26)
  %sign = shl <32 x i32> %vb, splat(i32 31)
  %sra = ashr <32 x i32> %sign, splat(i32 25)
  %res = or <32 x i32> %acc, %sra
  store <32 x i32> %res, ptr %a
  ret void
}

define void @ssra_disjoint_shift_or64xi32(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or64xi32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.s, vl64
; CHECK-NEXT:    ld1w { z0.s }, p0/z, [x0]
; CHECK-NEXT:    ld1w { z1.s }, p0/z, [x1]
; CHECK-NEXT:    lsr z0.s, z0.s, #26
; CHECK-NEXT:    lsl z1.s, z1.s, #31
; CHECK-NEXT:    ssra z0.s, z1.s, #25
; CHECK-NEXT:    st1w { z0.s }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <64 x i32>, ptr %a
  %vb = load <64 x i32>, ptr %b
  %acc = lshr <64 x i32> %va, splat(i32 26)
  %sign = shl <64 x i32> %vb, splat(i32 31)
  %sra = ashr <64 x i32> %sign, splat(i32 25)
  %res = or <64 x i32> %acc, %sra
  store <64 x i32> %res, ptr %a
  ret void
}

define <1 x i64> @ssra_disjoint_shift_or1xi64(<1 x i64> %a, <1 x i64> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or1xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ushr d0, d0, #58
; CHECK-NEXT:    shl d1, d1, #63
; CHECK-NEXT:    ssra d0, d1, #57
; CHECK-NEXT:    ret
  %acc = lshr <1 x i64> %a, splat(i64 58)
  %sign = shl <1 x i64> %b, splat(i64 63)
  %sra = ashr <1 x i64> %sign, splat(i64 57)
  %res = or <1 x i64> %acc, %sra
  ret <1 x i64> %res
}

define <2 x i64> @ssra_disjoint_shift_or2xi64(<2 x i64> %a, <2 x i64> %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or2xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ushr v0.2d, v0.2d, #58
; CHECK-NEXT:    shl v1.2d, v1.2d, #63
; CHECK-NEXT:    ssra v0.2d, v1.2d, #57
; CHECK-NEXT:    ret
  %acc = lshr <2 x i64> %a, splat(i64 58)
  %sign = shl <2 x i64> %b, splat(i64 63)
  %sra = ashr <2 x i64> %sign, splat(i64 57)
  %res = or <2 x i64> %acc, %sra
  ret <2 x i64> %res
}

define void @ssra_disjoint_shift_or4xi64(ptr %a, ptr %b) vscale_range(2,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or4xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d, vl4
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    ld1d { z1.d }, p0/z, [x1]
; CHECK-NEXT:    lsr z0.d, z0.d, #58
; CHECK-NEXT:    lsl z1.d, z1.d, #63
; CHECK-NEXT:    ssra z0.d, z1.d, #57
; CHECK-NEXT:    st1d { z0.d }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <4 x i64>, ptr %a
  %vb = load <4 x i64>, ptr %b
  %acc = lshr <4 x i64> %va, splat(i64 58)
  %sign = shl <4 x i64> %vb, splat(i64 63)
  %sra = ashr <4 x i64> %sign, splat(i64 57)
  %res = or <4 x i64> %acc, %sra
  store <4 x i64> %res, ptr %a
  ret void
}

define void @ssra_disjoint_shift_or8xi64(ptr %a, ptr %b) #0 {
; VBITS_GE_256-LABEL: ssra_disjoint_shift_or8xi64:
; VBITS_GE_256:       // %bb.0:
; VBITS_GE_256-NEXT:    ptrue p0.d, vl4
; VBITS_GE_256-NEXT:    mov x8, #4 // =0x4
; VBITS_GE_256-NEXT:    ld1d { z0.d }, p0/z, [x0, x8, lsl #3]
; VBITS_GE_256-NEXT:    ld1d { z1.d }, p0/z, [x1, x8, lsl #3]
; VBITS_GE_256-NEXT:    ld1d { z2.d }, p0/z, [x0]
; VBITS_GE_256-NEXT:    ld1d { z3.d }, p0/z, [x1]
; VBITS_GE_256-NEXT:    lsr z0.d, z0.d, #58
; VBITS_GE_256-NEXT:    lsl z1.d, z1.d, #63
; VBITS_GE_256-NEXT:    lsr z2.d, z2.d, #58
; VBITS_GE_256-NEXT:    lsl z3.d, z3.d, #63
; VBITS_GE_256-NEXT:    ssra z0.d, z1.d, #57
; VBITS_GE_256-NEXT:    ssra z2.d, z3.d, #57
; VBITS_GE_256-NEXT:    st1d { z0.d }, p0, [x0, x8, lsl #3]
; VBITS_GE_256-NEXT:    st1d { z2.d }, p0, [x0]
; VBITS_GE_256-NEXT:    ret
;
; VBITS_GE_512-LABEL: ssra_disjoint_shift_or8xi64:
; VBITS_GE_512:       // %bb.0:
; VBITS_GE_512-NEXT:    ptrue p0.d, vl8
; VBITS_GE_512-NEXT:    ld1d { z0.d }, p0/z, [x0]
; VBITS_GE_512-NEXT:    ld1d { z1.d }, p0/z, [x1]
; VBITS_GE_512-NEXT:    lsr z0.d, z0.d, #58
; VBITS_GE_512-NEXT:    lsl z1.d, z1.d, #63
; VBITS_GE_512-NEXT:    ssra z0.d, z1.d, #57
; VBITS_GE_512-NEXT:    st1d { z0.d }, p0, [x0]
; VBITS_GE_512-NEXT:    ret
  %va = load <8 x i64>, ptr %a
  %vb = load <8 x i64>, ptr %b
  %acc = lshr <8 x i64> %va, splat(i64 58)
  %sign = shl <8 x i64> %vb, splat(i64 63)
  %sra = ashr <8 x i64> %sign, splat(i64 57)
  %res = or <8 x i64> %acc, %sra
  store <8 x i64> %res, ptr %a
  ret void
}

define void @ssra_disjoint_shift_or16xi64(ptr %a, ptr %b) vscale_range(8,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or16xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d, vl16
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    ld1d { z1.d }, p0/z, [x1]
; CHECK-NEXT:    lsr z0.d, z0.d, #58
; CHECK-NEXT:    lsl z1.d, z1.d, #63
; CHECK-NEXT:    ssra z0.d, z1.d, #57
; CHECK-NEXT:    st1d { z0.d }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <16 x i64>, ptr %a
  %vb = load <16 x i64>, ptr %b
  %acc = lshr <16 x i64> %va, splat(i64 58)
  %sign = shl <16 x i64> %vb, splat(i64 63)
  %sra = ashr <16 x i64> %sign, splat(i64 57)
  %res = or <16 x i64> %acc, %sra
  store <16 x i64> %res, ptr %a
  ret void
}

define void @ssra_disjoint_shift_or32xi64(ptr %a, ptr %b) vscale_range(16,0) #0 {
; CHECK-LABEL: ssra_disjoint_shift_or32xi64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d, vl32
; CHECK-NEXT:    ld1d { z0.d }, p0/z, [x0]
; CHECK-NEXT:    ld1d { z1.d }, p0/z, [x1]
; CHECK-NEXT:    lsr z0.d, z0.d, #58
; CHECK-NEXT:    lsl z1.d, z1.d, #63
; CHECK-NEXT:    ssra z0.d, z1.d, #57
; CHECK-NEXT:    st1d { z0.d }, p0, [x0]
; CHECK-NEXT:    ret
  %va = load <32 x i64>, ptr %a
  %vb = load <32 x i64>, ptr %b
  %acc = lshr <32 x i64> %va, splat(i64 58)
  %sign = shl <32 x i64> %vb, splat(i64 63)
  %sra = ashr <32 x i64> %sign, splat(i64 57)
  %res = or <32 x i64> %acc, %sra
  store <32 x i64> %res, ptr %a
  ret void
}

declare <16 x i8> @llvm.aarch64.neon.ushl.v16i8(<16 x i8>, <16 x i8>)
declare <8 x i16> @llvm.aarch64.neon.ushl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i32> @llvm.aarch64.neon.ushl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i64> @llvm.aarch64.neon.ushl.v2i64(<2 x i64>, <2 x i64>)

declare <16 x i8> @llvm.aarch64.neon.sshl.v16i8(<16 x i8>, <16 x i8>)
declare <8 x i16> @llvm.aarch64.neon.sshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i32> @llvm.aarch64.neon.sshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i64> @llvm.aarch64.neon.sshl.v2i64(<2 x i64>, <2 x i64>)

attributes #0 = { "target-features"="+sve,+sve2" }
