; RUN: opt %s -passes='polly-custom<ast>' -polly-process-unprofitable \
; RUN:   -polly-astgen-computeout=1000000 -debug-only=polly-ast \
; RUN:   -disable-output 2>&1 | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64-unknown-linux-gnueabi"

define void @InitializeZeroMasks(i32 %0) {
entry:
  br label %if.end

if.end:                                           ; preds = %for.inc18, %entry
  %indvars.iv = phi i64 [ 1, %entry ], [ %indvars.iv.next, %for.inc18 ]
  br i1 true, label %if.end.1, label %for.end

if.end.1:                                         ; preds = %if.end
  %tobool.not.14 = icmp eq i32 %0, 0
  br i1 %tobool.not.14, label %if.end.14, label %for.end

if.end.14:                                        ; preds = %if.end.1
  %1 = trunc i64 %indvars.iv to i32
  %and.15 = and i32 %1, 1
  %tobool.not.15 = icmp eq i32 %and.15, 0
  br i1 %tobool.not.15, label %if.end14, label %for.end

for.end:                                          ; preds = %if.end.14, %if.end.1, %if.end
  %j.0119.lcssa = phi i8 [ 0, %if.end.1 ], [ 1, %if.end ], [ 0, %if.end.14 ]
  br label %if.then10

if.then10:                                        ; preds = %if.end14.13, %if.end14.12, %if.end14.11, %if.end14.10, %if.end14.9, %if.end14.8, %if.end14.7, %if.end14.6, %if.end14.5, %if.end14.4, %if.end14.3, %if.end14.2, %if.end14, %for.end
  %j.1121.lcssa.neg = phi i8 [ 1, %for.end ], [ 0, %if.end14 ], [ 0, %if.end14.13 ], [ 0, %if.end14.2 ], [ 0, %if.end14.3 ], [ 0, %if.end14.4 ], [ 0, %if.end14.5 ], [ 0, %if.end14.6 ], [ 0, %if.end14.7 ], [ 0, %if.end14.8 ], [ 0, %if.end14.9 ], [ 0, %if.end14.10 ], [ 0, %if.end14.11 ], [ 0, %if.end14.12 ]
  store i8 0, ptr null, align 1
  br label %for.inc18

if.end14:                                         ; preds = %if.end.14
  %and8.1 = and i32 %1, 2
  %tobool9.not.1 = icmp eq i32 %and8.1, 0
  %and8.2 = and i32 %1, 4
  %tobool9.not.2 = icmp eq i32 %and8.2, 0
  %or.cond = and i1 %tobool9.not.1, %tobool9.not.2
  br i1 %or.cond, label %if.end14.2, label %if.then10

if.end14.2:                                       ; preds = %if.end14
  %and8.3 = and i32 %1, 8
  %tobool9.not.3 = icmp eq i32 %and8.3, 0
  br i1 %tobool9.not.3, label %if.end14.3, label %if.then10

if.end14.3:                                       ; preds = %if.end14.2
  %and8.4 = and i32 %1, 16
  %tobool9.not.4 = icmp eq i32 %and8.4, 0
  br i1 %tobool9.not.4, label %if.end14.4, label %if.then10

if.end14.4:                                       ; preds = %if.end14.3
  %and8.5 = and i32 %1, 32
  %tobool9.not.5 = icmp eq i32 %and8.5, 0
  br i1 %tobool9.not.5, label %if.end14.5, label %if.then10

if.end14.5:                                       ; preds = %if.end14.4
  %and8.6 = and i32 %1, 64
  %tobool9.not.6 = icmp eq i32 %and8.6, 0
  br i1 %tobool9.not.6, label %if.end14.6, label %if.then10

if.end14.6:                                       ; preds = %if.end14.5
  %and8.7 = and i32 %1, 128
  %tobool9.not.7 = icmp eq i32 %and8.7, 0
  br i1 %tobool9.not.7, label %if.end14.7, label %if.then10

if.end14.7:                                       ; preds = %if.end14.6
  %and8.8 = and i32 %1, 256
  %tobool9.not.8 = icmp eq i32 %and8.8, 0
  br i1 %tobool9.not.8, label %if.end14.8, label %if.then10

if.end14.8:                                       ; preds = %if.end14.7
  %and8.9 = and i32 %1, 512
  %tobool9.not.9 = icmp eq i32 %and8.9, 0
  br i1 %tobool9.not.9, label %if.end14.9, label %if.then10

if.end14.9:                                       ; preds = %if.end14.8
  %and8.10 = and i32 %1, 1024
  %tobool9.not.10 = icmp eq i32 %and8.10, 0
  br i1 %tobool9.not.10, label %if.end14.10, label %if.then10

if.end14.10:                                      ; preds = %if.end14.9
  %and8.11 = and i32 %1, 2048
  %tobool9.not.11 = icmp eq i32 %and8.11, 0
  br i1 %tobool9.not.11, label %if.end14.11, label %if.then10

if.end14.11:                                      ; preds = %if.end14.10
  %and8.12 = and i32 %1, 4096
  %tobool9.not.12 = icmp eq i32 %and8.12, 0
  br i1 %tobool9.not.12, label %if.end14.12, label %if.then10

if.end14.12:                                      ; preds = %if.end14.11
  %and8.13 = and i32 %1, 8192
  %tobool9.not.13 = icmp eq i32 %and8.13, 0
  br i1 %tobool9.not.13, label %if.end14.13, label %if.then10

if.end14.13:                                      ; preds = %if.end14.12
  br i1 false, label %for.inc18, label %if.then10

for.inc18:                                        ; preds = %if.end14.13, %if.then10
  %indvars.iv.next = add i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv, 65536
  br i1 %exitcond.not, label %for.end20, label %if.end

for.end20:                                        ; preds = %for.inc18
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
