// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple avr-unknown-unknown -emit-llvm -o - %s | FileCheck %s

// Check that the parameter types match. This verifies pr43309.
// RUN: %clang_cc1 -triple avr-unknown-unknown -Wconversion -verify %s
// expected-no-diagnostics

// CHECK-LABEL: define dso_local i8 @bitrev8(
// CHECK-SAME: i8 noundef zeroext [[DATA:%.*]]) addrspace(1) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[DATA_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    store i8 [[DATA]], ptr [[DATA_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[DATA_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call addrspace(1) i8 @llvm.bitreverse.i8(i8 [[TMP0]])
// CHECK-NEXT:    ret i8 [[TMP1]]
//
unsigned char bitrev8(unsigned char data) {
    return __builtin_bitreverse8(data);
}


// CHECK-LABEL: define dso_local i16 @bitrev16(
// CHECK-SAME: i16 noundef [[DATA:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[DATA_ADDR:%.*]] = alloca i16, align 1
// CHECK-NEXT:    store i16 [[DATA]], ptr [[DATA_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[DATA_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call addrspace(1) i16 @llvm.bitreverse.i16(i16 [[TMP0]])
// CHECK-NEXT:    ret i16 [[TMP1]]
//
unsigned int bitrev16(unsigned int data) {
    return __builtin_bitreverse16(data);
}


// CHECK-LABEL: define dso_local i32 @bitrev32(
// CHECK-SAME: i32 noundef [[DATA:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[DATA_ADDR:%.*]] = alloca i32, align 1
// CHECK-NEXT:    store i32 [[DATA]], ptr [[DATA_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[DATA_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call addrspace(1) i32 @llvm.bitreverse.i32(i32 [[TMP0]])
// CHECK-NEXT:    ret i32 [[TMP1]]
//
unsigned long bitrev32(unsigned long data) {
    return __builtin_bitreverse32(data);
}

// CHECK-LABEL: define dso_local i64 @bitrev64(
// CHECK-SAME: i64 noundef [[DATA:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[DATA_ADDR:%.*]] = alloca i64, align 1
// CHECK-NEXT:    store i64 [[DATA]], ptr [[DATA_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[DATA_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call addrspace(1) i64 @llvm.bitreverse.i64(i64 [[TMP0]])
// CHECK-NEXT:    ret i64 [[TMP1]]
//
unsigned long long bitrev64(unsigned long long data) {
    return __builtin_bitreverse64(data);
}


// CHECK-LABEL: define dso_local i8 @rotleft8(
// CHECK-SAME: i8 noundef zeroext [[X:%.*]], i8 noundef zeroext [[Y:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    store i8 [[X]], ptr [[X_ADDR]], align 1
// CHECK-NEXT:    store i8 [[Y]], ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = urem i8 [[TMP1]], 8
// CHECK-NEXT:    [[TMP3:%.*]] = call addrspace(1) i8 @llvm.fshl.i8(i8 [[TMP0]], i8 [[TMP0]], i8 [[TMP2]])
// CHECK-NEXT:    ret i8 [[TMP3]]
//
unsigned char rotleft8(unsigned char x, unsigned char y) {
    return __builtin_rotateleft8(x, y);
}


// CHECK-LABEL: define dso_local i16 @rotleft16(
// CHECK-SAME: i16 noundef [[X:%.*]], i16 noundef [[Y:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i16, align 1
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i16, align 1
// CHECK-NEXT:    store i16 [[X]], ptr [[X_ADDR]], align 1
// CHECK-NEXT:    store i16 [[Y]], ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = urem i16 [[TMP1]], 16
// CHECK-NEXT:    [[TMP3:%.*]] = call addrspace(1) i16 @llvm.fshl.i16(i16 [[TMP0]], i16 [[TMP0]], i16 [[TMP2]])
// CHECK-NEXT:    ret i16 [[TMP3]]
//
unsigned int rotleft16(unsigned int x, unsigned int y) {
    return __builtin_rotateleft16(x, y);
}


// CHECK-LABEL: define dso_local i32 @rotleft32(
// CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[Y:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 1
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i32, align 1
// CHECK-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 1
// CHECK-NEXT:    store i32 [[Y]], ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = urem i32 [[TMP1]], 32
// CHECK-NEXT:    [[TMP3:%.*]] = call addrspace(1) i32 @llvm.fshl.i32(i32 [[TMP0]], i32 [[TMP0]], i32 [[TMP2]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
unsigned long rotleft32(unsigned long x, unsigned long y) {
    return __builtin_rotateleft32(x, y);
}

// CHECK-LABEL: define dso_local i64 @rotleft64(
// CHECK-SAME: i64 noundef [[X:%.*]], i64 noundef [[Y:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i64, align 1
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i64, align 1
// CHECK-NEXT:    store i64 [[X]], ptr [[X_ADDR]], align 1
// CHECK-NEXT:    store i64 [[Y]], ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = urem i64 [[TMP1]], 64
// CHECK-NEXT:    [[TMP3:%.*]] = call addrspace(1) i64 @llvm.fshl.i64(i64 [[TMP0]], i64 [[TMP0]], i64 [[TMP2]])
// CHECK-NEXT:    ret i64 [[TMP3]]
//
unsigned long long rotleft64(unsigned long long x, unsigned long long y) {
    return __builtin_rotateleft64(x, y);
}


// CHECK-LABEL: define dso_local i8 @rotright8(
// CHECK-SAME: i8 noundef zeroext [[X:%.*]], i8 noundef zeroext [[Y:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    store i8 [[X]], ptr [[X_ADDR]], align 1
// CHECK-NEXT:    store i8 [[Y]], ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = urem i8 [[TMP1]], 8
// CHECK-NEXT:    [[TMP3:%.*]] = call addrspace(1) i8 @llvm.fshr.i8(i8 [[TMP0]], i8 [[TMP0]], i8 [[TMP2]])
// CHECK-NEXT:    ret i8 [[TMP3]]
//
unsigned char rotright8(unsigned char x, unsigned char y) {
    return __builtin_rotateright8(x, y);
}


// CHECK-LABEL: define dso_local i16 @rotright16(
// CHECK-SAME: i16 noundef [[X:%.*]], i16 noundef [[Y:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i16, align 1
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i16, align 1
// CHECK-NEXT:    store i16 [[X]], ptr [[X_ADDR]], align 1
// CHECK-NEXT:    store i16 [[Y]], ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = urem i16 [[TMP1]], 16
// CHECK-NEXT:    [[TMP3:%.*]] = call addrspace(1) i16 @llvm.fshr.i16(i16 [[TMP0]], i16 [[TMP0]], i16 [[TMP2]])
// CHECK-NEXT:    ret i16 [[TMP3]]
//
unsigned int rotright16(unsigned int x, unsigned int y) {
    return __builtin_rotateright16(x, y);
}


// CHECK-LABEL: define dso_local i32 @rotright32(
// CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[Y:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 1
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i32, align 1
// CHECK-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 1
// CHECK-NEXT:    store i32 [[Y]], ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = urem i32 [[TMP1]], 32
// CHECK-NEXT:    [[TMP3:%.*]] = call addrspace(1) i32 @llvm.fshr.i32(i32 [[TMP0]], i32 [[TMP0]], i32 [[TMP2]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
unsigned long rotright32(unsigned long x, unsigned long y) {
    return __builtin_rotateright32(x, y);
}

// CHECK-LABEL: define dso_local i64 @rotright64(
// CHECK-SAME: i64 noundef [[X:%.*]], i64 noundef [[Y:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i64, align 1
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i64, align 1
// CHECK-NEXT:    store i64 [[X]], ptr [[X_ADDR]], align 1
// CHECK-NEXT:    store i64 [[Y]], ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = urem i64 [[TMP1]], 64
// CHECK-NEXT:    [[TMP3:%.*]] = call addrspace(1) i64 @llvm.fshr.i64(i64 [[TMP0]], i64 [[TMP0]], i64 [[TMP2]])
// CHECK-NEXT:    ret i64 [[TMP3]]
//
unsigned long long rotright64(unsigned long long x, unsigned long long y) {
    return __builtin_rotateright64(x, y);
}


// CHECK-LABEL: define dso_local i16 @byteswap16(
// CHECK-SAME: i16 noundef [[X:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i16, align 1
// CHECK-NEXT:    store i16 [[X]], ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call addrspace(1) i16 @llvm.bswap.i16(i16 [[TMP0]])
// CHECK-NEXT:    ret i16 [[TMP1]]
//
unsigned int byteswap16(unsigned int x) {
    return __builtin_bswap16(x);
}


// CHECK-LABEL: define dso_local i32 @byteswap32(
// CHECK-SAME: i32 noundef [[X:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 1
// CHECK-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call addrspace(1) i32 @llvm.bswap.i32(i32 [[TMP0]])
// CHECK-NEXT:    ret i32 [[TMP1]]
//
unsigned long byteswap32(unsigned long x) {
    return __builtin_bswap32(x);
}

// CHECK-LABEL: define dso_local i64 @byteswap64(
// CHECK-SAME: i64 noundef [[X:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i64, align 1
// CHECK-NEXT:    store i64 [[X]], ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call addrspace(1) i64 @llvm.bswap.i64(i64 [[TMP0]])
// CHECK-NEXT:    ret i64 [[TMP1]]
//
unsigned long long byteswap64(unsigned long long x) {
    return __builtin_bswap64(x);
}


// CHECK-LABEL: define dso_local float @powi(
// CHECK-SAME: float noundef [[X:%.*]], i16 noundef [[Y:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca float, align 1
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i16, align 1
// CHECK-NEXT:    store float [[X]], ptr [[X_ADDR]], align 1
// CHECK-NEXT:    store i16 [[Y]], ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = call addrspace(1) float @llvm.powi.f32.i16(float [[TMP0]], i16 [[TMP1]])
// CHECK-NEXT:    ret float [[TMP2]]
//
double powi(double x, int y) {
  return __builtin_powi(x, y);
}


// CHECK-LABEL: define dso_local float @powif(
// CHECK-SAME: float noundef [[X:%.*]], i16 noundef [[Y:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca float, align 1
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i16, align 1
// CHECK-NEXT:    store float [[X]], ptr [[X_ADDR]], align 1
// CHECK-NEXT:    store i16 [[Y]], ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = call addrspace(1) float @llvm.powi.f32.i16(float [[TMP0]], i16 [[TMP1]])
// CHECK-NEXT:    ret float [[TMP2]]
//
float powif(float x, int y) {
    return __builtin_powif(x, y);
}


// CHECK-LABEL: define dso_local float @powil(
// CHECK-SAME: float noundef [[X:%.*]], i16 noundef [[Y:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca float, align 1
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i16, align 1
// CHECK-NEXT:    store float [[X]], ptr [[X_ADDR]], align 1
// CHECK-NEXT:    store i16 [[Y]], ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[Y_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = call addrspace(1) float @llvm.powi.f32.i16(float [[TMP0]], i16 [[TMP1]])
// CHECK-NEXT:    ret float [[TMP2]]
//
long double powil(long double x, int y) {
    return __builtin_powil(x, y);
}


// CHECK-LABEL: define dso_local void @test_nop(
// CHECK-SAME: ) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call addrspace(1) void @llvm.avr.nop()
// CHECK-NEXT:    ret void
//
void test_nop(void) {
  __builtin_avr_nop();
}

// CHECK-LABEL: define dso_local void @test_sei(
// CHECK-SAME: ) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call addrspace(1) void @llvm.avr.sei()
// CHECK-NEXT:    ret void
//
void test_sei(void) {
  __builtin_avr_sei();
}

// CHECK-LABEL: define dso_local void @test_cli(
// CHECK-SAME: ) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call addrspace(1) void @llvm.avr.cli()
// CHECK-NEXT:    ret void
//
void test_cli(void) {
  __builtin_avr_cli();
}

// CHECK-LABEL: define dso_local void @test_sleep(
// CHECK-SAME: ) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call addrspace(1) void @llvm.avr.sleep()
// CHECK-NEXT:    ret void
//
void test_sleep(void) {
  __builtin_avr_sleep();
}

// CHECK-LABEL: define dso_local void @test_wdr(
// CHECK-SAME: ) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call addrspace(1) void @llvm.avr.wdr()
// CHECK-NEXT:    ret void
//
void test_wdr(void) {
  __builtin_avr_wdr();
}

// CHECK-LABEL: define dso_local i8 @test_swap(
// CHECK-SAME: i8 noundef zeroext [[A:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    store i8 [[A]], ptr [[A_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[A_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call addrspace(1) i8 @llvm.avr.swap(i8 [[TMP0]])
// CHECK-NEXT:    ret i8 [[TMP1]]
//
unsigned char test_swap(unsigned char a) {
  return __builtin_avr_swap(a);
}

// CHECK-LABEL: define dso_local i16 @test_fmul(
// CHECK-SAME: i8 noundef zeroext [[A:%.*]], i8 noundef zeroext [[B:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    store i8 [[A]], ptr [[A_ADDR]], align 1
// CHECK-NEXT:    store i8 [[B]], ptr [[B_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[A_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[B_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = call addrspace(0) i16 asm sideeffect "fmul $1, $2\0A\09movw $0, r0\0A\09clr r1", "=r,a,a,~{r0},~{r1}"(i8 [[TMP0]], i8 [[TMP1]])
// CHECK-NEXT:    ret i16 [[TMP2]]
//
unsigned int test_fmul(unsigned char a, unsigned char b) {
  return __builtin_avr_fmul(a, b);
}

// CHECK-LABEL: define dso_local i16 @test_fmuls(
// CHECK-SAME: i8 noundef signext [[A:%.*]], i8 noundef signext [[B:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    store i8 [[A]], ptr [[A_ADDR]], align 1
// CHECK-NEXT:    store i8 [[B]], ptr [[B_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[A_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[B_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = call addrspace(0) i16 asm sideeffect "fmuls $1, $2\0A\09movw $0, r0\0A\09clr r1", "=r,a,a,~{r0},~{r1}"(i8 [[TMP0]], i8 [[TMP1]])
// CHECK-NEXT:    ret i16 [[TMP2]]
//
int test_fmuls(signed char a, signed char b) {
  return __builtin_avr_fmuls(a, b);
}

// CHECK-LABEL: define dso_local i16 @test_fmulsu(
// CHECK-SAME: i8 noundef signext [[A:%.*]], i8 noundef zeroext [[B:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    store i8 [[A]], ptr [[A_ADDR]], align 1
// CHECK-NEXT:    store i8 [[B]], ptr [[B_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[A_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[B_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = call addrspace(0) i16 asm sideeffect "fmulsu $1, $2\0A\09movw $0, r0\0A\09clr r1", "=r,a,a,~{r0},~{r1}"(i8 [[TMP0]], i8 [[TMP1]])
// CHECK-NEXT:    ret i16 [[TMP2]]
//
int test_fmulsu(signed char a, unsigned char b) {
  return __builtin_avr_fmulsu(a, b);
}

// CHECK-LABEL: define dso_local void @test_nops(
// CHECK-SAME: ) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call addrspace(1) void @llvm.avr.nop()
// CHECK-NEXT:    call addrspace(1) void @llvm.avr.nop()
// CHECK-NEXT:    call addrspace(1) void @llvm.avr.nop()
// CHECK-NEXT:    ret void
//
void test_nops(void) {
  __builtin_avr_nops(3);
}

// CHECK-LABEL: define dso_local void @test_delay_cycles_small(
// CHECK-SAME: ) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call addrspace(0) void asm sideeffect "nop\0A\09", ""()
// CHECK-NEXT:    ret void
//
void test_delay_cycles_small(void) {
  // 1 cycle = 1 nop
  __builtin_avr_delay_cycles(1);
}

// CHECK-LABEL: define dso_local void @test_delay_cycles_two(
// CHECK-SAME: ) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call addrspace(0) void asm sideeffect "rjmp .+0\0A\09", ""()
// CHECK-NEXT:    ret void
//
void test_delay_cycles_two(void) {
  // 2 cycles = rjmp .+0
  __builtin_avr_delay_cycles(2);
}

// CHECK-LABEL: define dso_local void @test_delay_cycles_loop(
// CHECK-SAME: ) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call addrspace(0) void asm sideeffect "ldi r16, 4\0A\091: dec r16\0A\09brne 1b\0A\09", "~{r16}"()
// CHECK-NEXT:    ret void
//
void test_delay_cycles_loop(void) {
  // 12 cycles: 1-byte loop (4 iters = 12 cycles)
  __builtin_avr_delay_cycles(12);
}

// CHECK-LABEL: define dso_local void @test_delay_cycles_zero(
// CHECK-SAME: ) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call addrspace(0) void asm sideeffect "", ""()
// CHECK-NEXT:    ret void
//
void test_delay_cycles_zero(void) {
  // 0 cycles = empty inline asm
  __builtin_avr_delay_cycles(0);
}

// CHECK-LABEL: define dso_local i8 @test_insert_bits_identity(
// CHECK-SAME: i8 noundef zeroext [[BITS:%.*]], i8 noundef zeroext [[VAL:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[BITS_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[VAL_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    store i8 [[BITS]], ptr [[BITS_ADDR]], align 1
// CHECK-NEXT:    store i8 [[VAL]], ptr [[VAL_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[BITS_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[VAL_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = lshr i8 [[TMP0]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = and i8 [[TMP2]], 1
// CHECK-NEXT:    [[TMP4:%.*]] = shl i8 [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = or i8 0, [[TMP4]]
// CHECK-NEXT:    [[TMP6:%.*]] = lshr i8 [[TMP0]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = and i8 [[TMP6]], 1
// CHECK-NEXT:    [[TMP8:%.*]] = shl i8 [[TMP7]], 1
// CHECK-NEXT:    [[TMP9:%.*]] = or i8 [[TMP5]], [[TMP8]]
// CHECK-NEXT:    [[TMP10:%.*]] = lshr i8 [[TMP0]], 2
// CHECK-NEXT:    [[TMP11:%.*]] = and i8 [[TMP10]], 1
// CHECK-NEXT:    [[TMP12:%.*]] = shl i8 [[TMP11]], 2
// CHECK-NEXT:    [[TMP13:%.*]] = or i8 [[TMP9]], [[TMP12]]
// CHECK-NEXT:    [[TMP14:%.*]] = lshr i8 [[TMP0]], 3
// CHECK-NEXT:    [[TMP15:%.*]] = and i8 [[TMP14]], 1
// CHECK-NEXT:    [[TMP16:%.*]] = shl i8 [[TMP15]], 3
// CHECK-NEXT:    [[TMP17:%.*]] = or i8 [[TMP13]], [[TMP16]]
// CHECK-NEXT:    [[TMP18:%.*]] = lshr i8 [[TMP0]], 4
// CHECK-NEXT:    [[TMP19:%.*]] = and i8 [[TMP18]], 1
// CHECK-NEXT:    [[TMP20:%.*]] = shl i8 [[TMP19]], 4
// CHECK-NEXT:    [[TMP21:%.*]] = or i8 [[TMP17]], [[TMP20]]
// CHECK-NEXT:    [[TMP22:%.*]] = lshr i8 [[TMP0]], 5
// CHECK-NEXT:    [[TMP23:%.*]] = and i8 [[TMP22]], 1
// CHECK-NEXT:    [[TMP24:%.*]] = shl i8 [[TMP23]], 5
// CHECK-NEXT:    [[TMP25:%.*]] = or i8 [[TMP21]], [[TMP24]]
// CHECK-NEXT:    [[TMP26:%.*]] = lshr i8 [[TMP0]], 6
// CHECK-NEXT:    [[TMP27:%.*]] = and i8 [[TMP26]], 1
// CHECK-NEXT:    [[TMP28:%.*]] = shl i8 [[TMP27]], 6
// CHECK-NEXT:    [[TMP29:%.*]] = or i8 [[TMP25]], [[TMP28]]
// CHECK-NEXT:    [[TMP30:%.*]] = lshr i8 [[TMP0]], 7
// CHECK-NEXT:    [[TMP31:%.*]] = and i8 [[TMP30]], 1
// CHECK-NEXT:    [[TMP32:%.*]] = shl i8 [[TMP31]], 7
// CHECK-NEXT:    [[TMP33:%.*]] = or i8 [[TMP29]], [[TMP32]]
// CHECK-NEXT:    ret i8 [[TMP33]]
//
unsigned char test_insert_bits_identity(unsigned char bits, unsigned char val) {
  // Identity map: 0x76543210 — each nibble N maps bit N from 'bits'
  return __builtin_avr_insert_bits(0x76543210UL, bits, val);
}

// CHECK-LABEL: define dso_local i8 @test_insert_bits_reverse(
// CHECK-SAME: i8 noundef zeroext [[BITS:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[BITS_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    store i8 [[BITS]], ptr [[BITS_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[BITS_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = lshr i8 [[TMP0]], 7
// CHECK-NEXT:    [[TMP2:%.*]] = and i8 [[TMP1]], 1
// CHECK-NEXT:    [[TMP3:%.*]] = shl i8 [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = or i8 0, [[TMP3]]
// CHECK-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP0]], 6
// CHECK-NEXT:    [[TMP6:%.*]] = and i8 [[TMP5]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = shl i8 [[TMP6]], 1
// CHECK-NEXT:    [[TMP8:%.*]] = or i8 [[TMP4]], [[TMP7]]
// CHECK-NEXT:    [[TMP9:%.*]] = lshr i8 [[TMP0]], 5
// CHECK-NEXT:    [[TMP10:%.*]] = and i8 [[TMP9]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = shl i8 [[TMP10]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = or i8 [[TMP8]], [[TMP11]]
// CHECK-NEXT:    [[TMP13:%.*]] = lshr i8 [[TMP0]], 4
// CHECK-NEXT:    [[TMP14:%.*]] = and i8 [[TMP13]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = shl i8 [[TMP14]], 3
// CHECK-NEXT:    [[TMP16:%.*]] = or i8 [[TMP12]], [[TMP15]]
// CHECK-NEXT:    [[TMP17:%.*]] = lshr i8 [[TMP0]], 3
// CHECK-NEXT:    [[TMP18:%.*]] = and i8 [[TMP17]], 1
// CHECK-NEXT:    [[TMP19:%.*]] = shl i8 [[TMP18]], 4
// CHECK-NEXT:    [[TMP20:%.*]] = or i8 [[TMP16]], [[TMP19]]
// CHECK-NEXT:    [[TMP21:%.*]] = lshr i8 [[TMP0]], 2
// CHECK-NEXT:    [[TMP22:%.*]] = and i8 [[TMP21]], 1
// CHECK-NEXT:    [[TMP23:%.*]] = shl i8 [[TMP22]], 5
// CHECK-NEXT:    [[TMP24:%.*]] = or i8 [[TMP20]], [[TMP23]]
// CHECK-NEXT:    [[TMP25:%.*]] = lshr i8 [[TMP0]], 1
// CHECK-NEXT:    [[TMP26:%.*]] = and i8 [[TMP25]], 1
// CHECK-NEXT:    [[TMP27:%.*]] = shl i8 [[TMP26]], 6
// CHECK-NEXT:    [[TMP28:%.*]] = or i8 [[TMP24]], [[TMP27]]
// CHECK-NEXT:    [[TMP29:%.*]] = lshr i8 [[TMP0]], 0
// CHECK-NEXT:    [[TMP30:%.*]] = and i8 [[TMP29]], 1
// CHECK-NEXT:    [[TMP31:%.*]] = shl i8 [[TMP30]], 7
// CHECK-NEXT:    [[TMP32:%.*]] = or i8 [[TMP28]], [[TMP31]]
// CHECK-NEXT:    ret i8 [[TMP32]]
//
unsigned char test_insert_bits_reverse(unsigned char bits) {
  // Reverse map: 0x01234567 — reverses the bit order
  return __builtin_avr_insert_bits(0x01234567UL, bits, 0);
}

// CHECK-LABEL: define dso_local i8 @test_insert_bits_keep_val(
// CHECK-SAME: i8 noundef zeroext [[VAL:%.*]]) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[VAL_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    store i8 [[VAL]], ptr [[VAL_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[VAL_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = lshr i8 [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = and i8 [[TMP1]], 1
// CHECK-NEXT:    [[TMP3:%.*]] = shl i8 [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = or i8 0, [[TMP3]]
// CHECK-NEXT:    [[TMP5:%.*]] = lshr i8 [[TMP0]], 1
// CHECK-NEXT:    [[TMP6:%.*]] = and i8 [[TMP5]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = shl i8 [[TMP6]], 1
// CHECK-NEXT:    [[TMP8:%.*]] = or i8 [[TMP4]], [[TMP7]]
// CHECK-NEXT:    [[TMP9:%.*]] = lshr i8 [[TMP0]], 2
// CHECK-NEXT:    [[TMP10:%.*]] = and i8 [[TMP9]], 1
// CHECK-NEXT:    [[TMP11:%.*]] = shl i8 [[TMP10]], 2
// CHECK-NEXT:    [[TMP12:%.*]] = or i8 [[TMP8]], [[TMP11]]
// CHECK-NEXT:    [[TMP13:%.*]] = lshr i8 [[TMP0]], 3
// CHECK-NEXT:    [[TMP14:%.*]] = and i8 [[TMP13]], 1
// CHECK-NEXT:    [[TMP15:%.*]] = shl i8 [[TMP14]], 3
// CHECK-NEXT:    [[TMP16:%.*]] = or i8 [[TMP12]], [[TMP15]]
// CHECK-NEXT:    [[TMP17:%.*]] = lshr i8 [[TMP0]], 4
// CHECK-NEXT:    [[TMP18:%.*]] = and i8 [[TMP17]], 1
// CHECK-NEXT:    [[TMP19:%.*]] = shl i8 [[TMP18]], 4
// CHECK-NEXT:    [[TMP20:%.*]] = or i8 [[TMP16]], [[TMP19]]
// CHECK-NEXT:    [[TMP21:%.*]] = lshr i8 [[TMP0]], 5
// CHECK-NEXT:    [[TMP22:%.*]] = and i8 [[TMP21]], 1
// CHECK-NEXT:    [[TMP23:%.*]] = shl i8 [[TMP22]], 5
// CHECK-NEXT:    [[TMP24:%.*]] = or i8 [[TMP20]], [[TMP23]]
// CHECK-NEXT:    [[TMP25:%.*]] = lshr i8 [[TMP0]], 6
// CHECK-NEXT:    [[TMP26:%.*]] = and i8 [[TMP25]], 1
// CHECK-NEXT:    [[TMP27:%.*]] = shl i8 [[TMP26]], 6
// CHECK-NEXT:    [[TMP28:%.*]] = or i8 [[TMP24]], [[TMP27]]
// CHECK-NEXT:    [[TMP29:%.*]] = lshr i8 [[TMP0]], 7
// CHECK-NEXT:    [[TMP30:%.*]] = and i8 [[TMP29]], 1
// CHECK-NEXT:    [[TMP31:%.*]] = shl i8 [[TMP30]], 7
// CHECK-NEXT:    [[TMP32:%.*]] = or i8 [[TMP28]], [[TMP31]]
// CHECK-NEXT:    ret i8 [[TMP32]]
//
unsigned char test_insert_bits_keep_val(unsigned char val) {
  // 0xFFFFFFFF — all nibbles are 0xF, keep all bits from 'val'
  return __builtin_avr_insert_bits(0xFFFFFFFFUL, 0, val);
}

// CHECK-LABEL: define dso_local i8 @test_flash_segment_flash(
// CHECK-SAME: ) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P:%.*]] = alloca ptr addrspace(1), align 1
// CHECK-NEXT:    store ptr addrspace(1) null, ptr [[P]], align 1
// CHECK-NEXT:    ret i8 0
//
signed char test_flash_segment_flash(void) {
  const __attribute__((address_space(1))) unsigned char *p = 0;
  // __flash = addrspace(1), segment 0
  return __builtin_avr_flash_segment(p);
}

// CHECK-LABEL: define dso_local i8 @test_flash_segment_ram(
// CHECK-SAME: ) addrspace(1) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P:%.*]] = alloca ptr, align 1
// CHECK-NEXT:    store ptr null, ptr [[P]], align 1
// CHECK-NEXT:    ret i8 -1
//
signed char test_flash_segment_ram(void) {
  const unsigned char *p = 0;
  // RAM = addrspace(0), segment -1
  return __builtin_avr_flash_segment(p);
}
